twake/frontend/src/app/components/Inputs/Input.js, twake/frontend/src/app/scenes/Login/Signin/Signin.js
=> #29 Add error message if password/mail is invalid during subscription

twake/frontend/src/app/components/ObjectModal/ObjectModal.js, twake/frontend/src/app/components/Twacode/blocks/Chan.js, twake/frontend/src/app/components/Twacode/blocks/User.js, twake/frontend/src/app/components/UserCard/User-Card.scss, twake/frontend/src/app/components/UserCard/UserCard.js, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.js, twake/frontend/src/app/services/Menus/MenusManager.js, twake/frontend/src/app/services/languages/locale/en.js
=> #20 Add user card informations popup

twake/frontend/src/app/components/ObjectModal/ObjectModal.js, twake/frontend/src/app/components/Twacode/blocks/Chan.js, twake/frontend/src/app/components/Twacode/blocks/User.js, twake/frontend/src/app/components/UserCard/User-Card.scss, twake/frontend/src/app/components/UserCard/UserCard.js, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.js, twake/frontend/src/app/services/Menus/MenusManager.js, twake/frontend/src/app/services/languages/locale/en.js
=> 🌟 Add user card informations popup

twake/frontend/package.json, twake/frontend/src/app/components/ColorPicker/ColorPicker.js, twake/frontend/src/app/environment/version.ts, twake/frontend/src/app/services/login/login.js
=> Update dev branch

.github/workflows/saas-update-backend.yml, .github/workflows/saas-update-front.yml
🐳 Fix deployment of dockers (#75)
=> 🐳 Fix deployment of dockers (#75)

twake/backend/core/src/Twake/Core/Services/TwakeMailer.php
Allow unconfigured DMIK in TwakeMailer Service
=> Improvement of TwakeMailer Service

twake/frontend/src/app/scenes/Apps/Messages/Message/Message.js
=> #74 Fix user popup for application names in messages

twake/backend/core/app/Configuration/Parameters.php.dist, twake/backend/core/src/Twake/Core/Controller/Version.php, twake/frontend/src/app/scenes/Login/LoginView/LoginView.js
=> #78 Allow disabling account creation with parameters file

twake/frontend/src/app/components/Parameters/Attribute.js, twake/frontend/src/app/scenes/App/Popup/CreateCompanyView/CreateCompanyView.js, twake/frontend/src/app/scenes/App/Popup/CreateWorkspacePage/CreateWorkspacePage.js, twake/frontend/src/app/scenes/App/Popup/SecondMail/SecondMail.js, twake/frontend/src/app/scenes/App/Popup/UserParameter/UserParameter.js, twake/frontend/src/app/scenes/App/Popup/WelcomePage/WelcomePage.js, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspaceApps.js, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspaceAppsSearch.js, twake/frontend/src/app/scenes/Login/ForgotPassword/ForgotPassword.js, twake/frontend/src/app/scenes/Login/Signin/Signin.js, twake/frontend/src/app/scenes/Login/VerifyMail/VerifyMail.js, twake/frontend/src/app/scenes/app.js
=> #87 Fix page refresh and routing problem when saving account settings

twake/frontend/src/app/components/Tooltip/Tooltip.js, twake/frontend/src/app/components/Tooltip/Tooltip.scss, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspacePartner.js, twake/frontend/src/app/scenes/Apps/Messages/Message/Responses.js, twake/frontend/src/app/services/workspaces/workspaces_users.js
=> #146 Fix frontend issues 

twake/frontend/src/app/services/channels/channels.js
=> #136 Fix favicon bug

twake/backend/core/src/Twake/Core/Command/MappingCommand.php, twake/backend/core/src/Twake/Discussion/Command/MessageToDispatchQueueCommand.php, twake/backend/core/src/Twake/Notifications/Services/Notifications.php, twake/backend/core/src/Twake/Users/Entity/User.php, twake/backend/core/src/Twake/Users/Services/Users.php, twake/frontend/src/app/components/UserListManager/UserListManager.js, twake/frontend/src/app/services/languages/locale/en.js
Fix substr to mb_substr and add try-catch to queue
=> 🛠 Fix substr to mb_substr and add try-catch to queue

twake/frontend/src/app/components/Icon/Icon.js, twake/frontend/src/app/components/Icon/unicons.scss, twake/frontend/src/app/components/InlineTagPicker/InlineTagPicker.js, twake/frontend/src/app/components/InlineTagPicker/InlineTagPicker.scss, twake/frontend/src/app/components/Parameters/Attribute.js, twake/frontend/src/app/components/constants.scss, twake/frontend/src/app/scenes/App/MainView/MainView.js, twake/frontend/src/app/scenes/App/Popup/AppsParameters/AppsParameters.js, twake/frontend/src/app/scenes/App/Popup/AppsParameters/Pages/Pages.scss, twake/frontend/src/app/scenes/App/Popup/AppsParameters/Pages/WorkspaceApps.js, twake/frontend/src/app/scenes/App/Popup/AppsParameters/Pages/WorkspaceAppsCreator.js, twake/frontend/src/app/scenes/App/Popup/AppsParameters/Pages/WorkspaceAppsEditor.js, twake/frontend/src/app/scenes/App/Popup/AppsParameters/Pages/WorkspaceAppsInformations.js, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspaceApps.js, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspaceAppsSearch.js, twake/frontend/src/app/services/languages/locale/de.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/es.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/languages/locale/ja.js, twake/frontend/src/app/services/languages/locale/ru.js, twake/frontend/src/app/services/workspaces/workspaces_apps.js
=> #193 Improve applications and connectors management

twake/frontend/src/app/components/AutoHeight/AutoHeight.js, twake/frontend/src/app/components/ObjectModal/ObjectModal.js, twake/frontend/src/app/components/Twacode/PseudoMarkdownDictionary.js, twake/frontend/src/app/scenes/App/ChannelsBar/Channel.js, twake/frontend/src/app/scenes/App/ChannelsBar/ChannelTemplateEditor.js, twake/frontend/src/app/scenes/App/ChannelsBar/ChannelsWorkspace/ChannelsWorkspace.js, twake/frontend/src/app/scenes/App/MainView/MainView.js, twake/frontend/src/app/scenes/App/MainView/MainView.scss, twake/frontend/src/app/services/Twacode/pseudoMarkdownCompiler.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
=> #165 Add channel description feature and improve channel creation/edition

twake/frontend/src/app/components/AutoHeight/AutoHeight.js, twake/frontend/src/app/components/ObjectModal/ObjectModal.js, twake/frontend/src/app/components/Twacode/PseudoMarkdownDictionary.js, twake/frontend/src/app/scenes/App/ChannelsBar/Channel.js, twake/frontend/src/app/scenes/App/ChannelsBar/ChannelTemplateEditor.js, twake/frontend/src/app/scenes/App/ChannelsBar/ChannelsWorkspace/ChannelsWorkspace.js, twake/frontend/src/app/scenes/App/MainView/MainView.js, twake/frontend/src/app/scenes/App/MainView/MainView.scss, twake/frontend/src/app/services/Twacode/pseudoMarkdownCompiler.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
=> 🌟  Add channel description feature

twake/frontend/src/app/components/Twacode/blocks/User.js, twake/frontend/src/app/components/UserCard/User-Card.scss, twake/frontend/src/app/components/UserCard/UserCard.js, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.js
=> #74 Add user card popup when somebody is mentionned in conversation

twake/frontend/src/app/components/Alert/Confirm.js, twake/frontend/src/app/components/Buttons/Button.js, twake/frontend/src/app/scenes/App/Popup/WorkspaceParameter/Pages/WorkspaceIdentity.js, twake/frontend/src/app/services/AlertManager/AlertManager.js, twake/frontend/src/app/services/workspaces/workspaces.js
=> 🛠  Fix delete workspace button (#257)

twake/frontend/public/public/viewer/ImageViewer/viewer.html, twake/frontend/public/public/viewer/PDFViewer/viewer.html, twake/frontend/public/public/viewer/PDFViewer/viewer.js, twake/frontend/src/app/scenes/Apps/Drive/Viewer/Viewer.js
=> #244 Add loader for pdf and image viewer

twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessagesList.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/GoToBottom.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/ScrollerParent.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/Threads.scss, twake/frontend/src/app/services/Apps/Messages/MessagesListUtils.ts
Increase number of pre-rendered message and avoid unwanted state update in message main listing
=> Fix performances of messages feed

twake/frontend/src/app/scenes/App/ChannelsBar/CurrentUser/CurrentUser.js, twake/frontend/src/app/scenes/App/Popup/UserParameter/UserParameter.js
=> #143 Fix notification settings button

twake/frontend/src/app/components/Drive/Drive.scss, twake/frontend/src/app/components/Drive/File.js, twake/frontend/src/app/components/Drive/UI/File.js, twake/frontend/src/app/components/Twacode/PseudoMarkdownDictionary.js, twake/frontend/src/app/components/Twacode/Twacode.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/AttachedFiles.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/InputOptions.tsx, twake/frontend/src/app/services/Apps/Messages/MessageEditors.ts, twake/frontend/src/app/services/Apps/Messages/Messages.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
=> #283 Allow multiple documents in a single post

twake/frontend/src/app/components/AutoComplete/AutoComplete.tsx, twake/frontend/src/app/components/Uploads/UploadZone.js, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/AttachedFiles.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/InputAutocomplete.tsx, twake/frontend/src/app/services/Apps/Messages/MessageEditors.ts, twake/frontend/src/app/services/Apps/Messages/Messages.js
* #142 Allow ctrl-v image in message
* #283 Fix margin between files attachements
=> 🌟 #142 Allow ctrl-v image in message

twake/backend/node/package-lock.json, twake/backend/node/package.json, twake/backend/node/src/core/platform/framework/api.ts, twake/backend/node/src/core/platform/framework/factory.ts, twake/backend/node/src/core/platform/platform.ts
This is something I wanted to do when I started to work on the framework. Using RxJS here makes sense to manage component states. This is just the beginning since we want to build something really reactive on the backend.
I will add the unit tests for all of this asap!
=> 🤘🏻 Use RxJS instead of promises to manage service states

twake/backend/node/README.md
=> #380 Add the platform documentation

twake/backend/node/src/core/platform/framework/api.ts, twake/backend/node/src/core/platform/framework/utils/component-utils.ts, twake/backend/node/src/core/platform/platform.ts, twake/backend/node/src/services/webserver/index.ts, twake/backend/node/test/e2e/setup/index.ts
=> Add stop to platform

twake/backend/node/config/default.json, twake/backend/node/package-lock.json, twake/backend/node/package.json, twake/backend/node/src/services/webserver/index.ts
=> Add CORS plugin

twake/backend/core/src/Twake/Channels/Services/ChannelsNotificationsSystem.php, twake/frontend/src/app/components/Uploads/UploadZone.js, twake/frontend/src/app/scenes/App/MainView/MainView.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/NewThread.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.scss, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageEdition.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx, twake/frontend/src/app/scenes/Apps/Messages/Messages.scss, twake/frontend/src/app/scenes/Apps/Messages/Parts/ScrollerParent.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/Thread.tsx, twake/frontend/src/app/services/Apps/Messages/MessagesListUtils.ts, twake/frontend/src/app/services/workspaces/workspaces_users.js
Fix issues from last update (Q3.107)
=> 🩹 Feature/2020.q3.dev fix

twake/backend/node/README.md, twake/backend/node/src/core/platform/services/realtime/services/entity-manager.ts, twake/backend/node/test/unit/core/platform/framework/decorators/realtime/created.test.ts, twake/backend/node/test/unit/core/platform/framework/decorators/realtime/deleted.test.ts, twake/backend/node/test/unit/core/platform/framework/decorators/realtime/updated.test.ts
=> #462 Add room name in the realtime event

twake/frontend/src/app/app.tsx, twake/frontend/src/app/components/Inputs/InputWithIcon.js, twake/frontend/src/app/components/Inputs/Inputs.scss, twake/frontend/src/app/components/ObjectModal/ObjectModal.js, twake/frontend/src/app/components/ObjectModal/ObjectModal.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelTemplateEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelWorkspaceEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.js, twake/frontend/src/app/scenes/Client/ChannelsBar/NewDirectMessagesPopup.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/services/languages/locale/de.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/es.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/languages/locale/ja.js, twake/frontend/src/app/services/languages/locale/ru.js, twake/frontend/src/app/theme.less
=> #517 Add Twake theme overriding ant design style and apply antd components for channel creation

twake/frontend/src/app/components/Drive/VersionDetails.js, twake/frontend/src/app/components/ObjectModal/DeprecatedObjectModal.js, twake/frontend/src/app/components/ObjectModal/DeprecatedObjectModal.scss, twake/frontend/src/app/components/ObjectModal/ObjectModal.scss, twake/frontend/src/app/components/ObjectModal/ObjectModal.tsx, twake/frontend/src/app/components/SearchPopup/Parts/EventsFilter.js, twake/frontend/src/app/components/SearchPopup/Parts/FilesFilter.js, twake/frontend/src/app/components/SearchPopup/Parts/MessagesFilter.js, twake/frontend/src/app/components/SearchPopup/Parts/TasksFilter.js, twake/frontend/src/app/models/Channel.ts, twake/frontend/src/app/scenes/Apps/Tasks/Board/Task/TaskDetails.js, twake/frontend/src/app/scenes/Apps/Tasks/Board/Task/TaskEditor.js, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelMembersEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelMembersList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelWorkspaceEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/NewDirectMessagesPopup.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/CreateCompanyAccount.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/theme.less
=> #557 Add channel members list popup

twake/backend/core/src/DevelopersApiV1/Messages/Controller/Message.php, twake/backend/core/src/Twake/Discussion/Controller/Discussion.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/AppView.tsx, twake/frontend/src/app/scenes/Client/MainView/MainContent.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ApplicationHeader/ApplicationHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/MainHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.scss, twake/frontend/src/app/scenes/Client/MainView/MainView.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/WorkspacesBar.tsx, twake/frontend/src/app/services/channels/SideService.ts
- Add websocket unencrypted route
- Add get single message route
=> Mobile backend requirements update

twake/frontend/src/app/components/Channel/UserChannelParts.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelMembersList.tsx, twake/frontend/src/app/scenes/Client/MainView/MainContent.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/TabsTemplateEditor.tsx
=> #602 Allow tab creation and add default Discussion tab

twake/frontend/src/app/models/Tab.ts, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.scss, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tab.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.scss, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/TabsTemplateEditor.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/workspaces/workspaces_apps.js, twake/frontend/src/app/theme.less
=> #606 Improve tabs design & allow renaming or deleting a tab based on user roles

twake/frontend/src/app/components/SearchPopup/SearchPopup.js, twake/frontend/src/app/scenes/App.tsx, twake/frontend/src/app/scenes/BadDevice/BadDevice.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/theme.less
Iphone 5:
Iphone 6-7-8 plus:
Ipad:
Small screen: 
Large screen:
Xlarge screen:
=> #625 Responsive Channel header and fix bug in ChannelIntermediate component

twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsWorkspace/WorkspaceChannels.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/WorkspaceChannelRow.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Workspace/workspace.tsx
=> Refacto join channels with autocomplete

twake/frontend/src/app/scenes/Login/login.scss, twake/frontend/src/app/services/login/login.js
This apply to login , sign up  and forgot password pages
=> #634 Add media queries for mobile devices and force login component if the typed url is '/login'

twake/frontend/package.json, twake/frontend/src/app/components/ScrollHiddenComponents/Beacon.tsx, twake/frontend/src/app/components/ScrollHiddenComponents/HiddenNotificationService.ts, twake/frontend/src/app/components/ScrollHiddenComponents/HiddenNotificationsButton.tsx, twake/frontend/src/app/components/ScrollHiddenComponents/Notifications.scss, twake/frontend/src/app/components/ScrollHiddenComponents/ScrollWithHiddenComponents.tsx, twake/frontend/src/app/components/constants.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/Channel.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/yarn.lock
=>  #227 Add indicator when there is a notification from a hidden channel / contact 

twake/frontend/src/app/components/Menus/MenuComponent.js, twake/frontend/src/app/components/ObjectModal/DeprecatedObjectModal.js, twake/frontend/src/app/components/ObjectModal/DeprecatedObjectModal.scss, twake/frontend/src/app/scenes/Apps/Calendar/Calendar.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/EventCreation.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/EventDetails.js, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelMembersEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelMembersList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelTemplateEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelWorkspaceEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/NewDirectMessagesPopup.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/WorkspaceChannelRow.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Header/MemberChannelRow.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Header/MemberChannelRow.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/TabsTemplateEditor.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
=> #653 Multiple bug fixes

twake/frontend/src/app/services/workspaces/workspaces.js
=> #693 Generate default channel in brand new workspace

twake/frontend/src/app/components/Menus/Menu.scss, twake/frontend/src/app/components/UserListManager/UserListManager.scss, twake/frontend/src/app/components/UserListManager/UserListManager.tsx, twake/frontend/src/app/components/ui/UserOrMail.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/EventCreation.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/EventModification.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/Modals.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/NewDirectMessagesPopup.tsx
https://user-images.githubusercontent.com/36481167/103880102-f8aa4b00-50d8-11eb-8afe-710d7494cb9b.mp4
=> #687 Fix UserListManager in Q4

twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CurrentUser.js, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUser.scss, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUserFromTwakeConsole.tsx, twake/frontend/src/app/scenes/Client/Popup/CreateCompanyView/CreateCompanyView.js, twake/frontend/src/app/scenes/Client/Popup/CreateWorkspacePage/CreateWorkspacePage.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Members.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/WorkspaceParameter.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
https://user-images.githubusercontent.com/36481167/103920432-99b4f800-5111-11eb-80a6-912a8937935c.mp4
=> #683 Adapt the add collaborators feature for Twake Console

twake/backend/node/src/services/channels/services/tab/service.ts, twake/frontend/src/app/components/AutoCompleteExtended/AutoCompleteExtended.tsx, twake/frontend/src/app/components/EmojiPicker/EmojiPicker.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsUser/ChannelsUser.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CurrentUser.js, twake/frontend/src/app/scenes/Client/ChannelsBar/Workspace/workspace.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/Components/Group.js, twake/frontend/src/app/services/Collections/Collection.ts, twake/frontend/src/app/services/Collections/Transport/CollectionFindCompletion.ts, twake/frontend/src/app/services/Collections/Transport/TransportSocket.ts, twake/frontend/src/app/services/CollectionsReact/Collections.ts, twake/frontend/src/app/services/Depreciated/Collections/SecuredConnection.js, twake/frontend/src/app/services/channels/channels.js, twake/frontend/src/app/services/user/notifications.tsx
* Fix important bug in collections
* Implement data reload on reconnect
* Fix emojis, remove logs, Re-fix tabs
=> 🛠  Fix more issues

twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/MessageAndTimeSeparator.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/Options.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessagesList.tsx
https://user-images.githubusercontent.com/36481167/104191095-557d6c80-541d-11eb-833c-5134fbc7a9cb.mp4
=> #444 Hide drag icon and showMessage in thread view

twake/frontend/src/app/components/Banner/Banner.scss, twake/frontend/src/app/components/Banner/Banner.tsx, twake/frontend/src/app/components/NewVersion/NewVersionComponent.tsx, twake/frontend/src/app/components/NewVersion/NewVersionModal.tsx, twake/frontend/src/app/components/ObjectModal/ObjectModal.tsx, twake/frontend/src/app/models/Configuration.ts, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
https://user-images.githubusercontent.com/36481167/104344377-5d144280-54fd-11eb-9353-f6427492242f.mp4
=> #239 Notify when new features are available and propose to reload the app

twake/frontend/src/app/components/Drive/DriveElement.js, twake/frontend/src/app/components/NewVersion/NewVersionComponent.tsx, twake/frontend/src/app/scenes/Apps/Drive/Drive.js, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.scss, twake/frontend/src/app/scenes/Client/MainView/PublicMainView.js, twake/frontend/src/app/services/RouterService.ts, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
https://user-images.githubusercontent.com/36481167/104622185-3ab32e00-5691-11eb-8cec-6f98b83f8398.mp4
https://user-images.githubusercontent.com/36481167/104718594-63880180-572b-11eb-8f9d-2139f5274a6b.mp4
=> #563 Reimplement public drive access with new router

twake/backend/node/src/services/channels/entities/channel.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/cassandra.ts, twake/backend/node/src/services/channels/services/channel/mongo.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/index.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/channels/services/pubsub/index.ts, twake/backend/node/src/services/channels/services/pubsub/new-channel-message/index.ts, twake/backend/node/src/services/channels/services/pubsub/new-direct-channel-message/index.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/notifications/api.ts, twake/backend/node/src/services/notifications/entities/channel-member-notification-preferences.ts, twake/backend/node/src/services/notifications/entities/index.ts, twake/backend/node/src/services/notifications/entities/user-notification-badges.ts, twake/backend/node/src/services/notifications/services/engine/processors/channel-member-created/index.ts, twake/backend/node/src/services/notifications/services/engine/processors/channel-member-deleted/index.ts, twake/backend/node/test/http/direct-channels.http
=> Several direct channels fixes

twake/backend/core/src/Twake/Core/Command/MappingCommand.php
It was boring to wait so much time for nothing...
=> #780 Do not wait for ES when disabled

twake/backend/core/app/Configuration/Parameters.php.dist, twake/backend/core/src/Twake/Drive/Services/DownloadFile.php, twake/backend/core/src/Twake/Drive/Services/DriveFileSystem.php, twake/backend/core/src/Twake/Drive/Services/OldFileSystem/Adapter_AWS_DriveFileSystem.php, twake/backend/core/src/Twake/Drive/Services/OldFileSystem/Adapter_OpenStack_DriveFileSystem.php, twake/backend/core/src/Twake/Drive/Services/OldFileSystem/DriveAdapterSelector.php, twake/backend/core/src/Twake/Drive/Services/Storage/Adapter_AWS.php, twake/backend/core/src/Twake/Drive/Services/Storage/Adapter_Local.php, twake/backend/core/src/Twake/Drive/Services/Storage/Adapter_OpenStack.php, twake/backend/core/src/Twake/Drive/Services/Storage/StorageManager.php, twake/backend/core/src/Twake/Upload/Services/AWS_Uploader.php, twake/backend/core/src/Twake/Upload/Services/OpenStack_Uploader.php, twake/backend/core/src/Twake/Users/Controller/UsersAccount.php, twake/backend/core/src/Twake/Workspaces/Controller/Group.php, twake/backend/core/src/Twake/Workspaces/Controller/WorkspaceData.php, twake/frontend/src/app/environment/environment.ts.dist, twake/frontend/src/app/environment/environment.ts.dist.dev, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CompanyHeader/CompanyHeader.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Members.js, twake/frontend/src/app/services/languages/locale/de.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/es.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/languages/locale/ja.js, twake/frontend/src/app/services/languages/locale/ru.js, twake/frontend/src/app/services/login/login.js
Changes in configuration:
```
"storage" => [
"S3" => [
...
]
```
becomes
```
"storage" => [
"providers" => [
[
"label" => "someawss3",
"type" => "S3",
...
],
[...],
...
]
```
=> 🧺 Multi-buckets feature

twake/backend/node/config/custom-environment-variables.json, twake/backend/node/config/default.json, twake/backend/node/src/core/platform/services/database/index.ts, twake/backend/node/src/core/platform/services/database/services/connector-factory.ts, twake/backend/node/src/core/platform/services/database/services/index.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/abstract-connector.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/query-builder.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/mongodb.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/typeTransforms.ts, twake/backend/node/src/core/platform/services/database/services/orm/types.ts, twake/backend/node/src/core/platform/services/database/services/orm/utils.ts, twake/backend/node/src/services/channels/entities/channel-activity.ts, twake/backend/node/src/services/channels/entities/tab.ts, twake/backend/node/test/http/tabs.http
The work for encryption at rest is ready with Cassandra but not started with Mongo.
=> WIP: Encryption at rest with Cassandra

twake/frontend/src/app/services/Collections/Collection.ts, twake/frontend/src/app/services/Collections/Collections.ts, twake/frontend/src/app/services/Collections/Storage.ts, twake/frontend/src/app/services/Collections/Transport/CollectionFindCompletion.ts, twake/frontend/src/app/services/Collections/Transport/CollectionTransportSockets.ts, twake/frontend/src/app/services/Collections/__tests__/CollectionStorage.test.ts, twake/frontend/src/app/services/CollectionsReact/Collections.ts, twake/frontend/src/app/services/CollectionsReact/__tests__/CollectionReact.test.tsx
Some little cleanup on how we init and access to the CollectionStorage. Digging into this did not show any issue on the performance side but was nice to discover this sub module.
=> Cleanup access to collection store

twake/frontend/src/app/components/Inputs/InputWithIcon.js, twake/frontend/src/app/components/Inputs/InputWithSelect.scss, twake/frontend/src/app/components/Inputs/InputWithSelect.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelTemplateEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelWorkspaceEditor.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/theme.less
https://user-images.githubusercontent.com/36481167/106031280-62fa4e00-60cf-11eb-8714-32be6bb8fe8c.mp4
=> 📁  #330 Allow changing or create the group of a channel (#823)

twake/backend/core/src/Twake/Core/Services/AccessManager.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/core/src/Twake/Notifications/Command/NodePushNotifications.php, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/core/platform/services/phpnode/index.ts, twake/backend/node/src/core/platform/services/realtime/services/entity-manager.ts, twake/backend/node/src/core/platform/services/realtime/types.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/channels/web/controllers/member.ts, twake/backend/node/src/services/channels/web/schemas.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/notifications/services/engine/processors/new-channel-message/index.ts, twake/backend/node/src/services/notifications/services/engine/processors/push-to-users/index.ts, twake/backend/node/src/services/notifications/types.ts, twake/backend/node/src/services/notifications/web/controllers/notification.ts, twake/backend/node/src/services/notifications/web/routes.ts, twake/backend/node/test/http/badges.http, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsWorkspace/WorkspaceChannels.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelCategory.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/services/Collections/Collection.ts, twake/frontend/src/app/services/Collections/EventEmitter.ts, twake/frontend/src/app/services/Collections/Transport/CollectionTransportSockets.ts, twake/frontend/src/app/services/CollectionsReact/Collections.ts, twake/frontend/src/app/services/CollectionsReact/__tests__/CollectionReact.test.tsx, twake/frontend/src/app/services/user/notifications.tsx
=> 🎈 #312 #812 Notifications push improvements

twake/frontend/src/app/components/Inputs/InputWithSelect.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList.tsx
Ref to #831 #833 #828
https://user-images.githubusercontent.com/36481167/106178352-f304ca00-6199-11eb-8f76-cd1e8a04444d.mp4
https://user-images.githubusercontent.com/36481167/106261578-06f40e80-6222-11eb-8f3d-8795517b804c.mp4
=> 🛠  Multiple fixes 

.vscode/launch.json, twake/backend/node/package.json, twake/docker-compose.yml.dist.dev, twake/docker/twake-node/Dockerfile.dev
1. From VSCode, `Run`, `Start Debugging` and choose the right target
2. Add breakpoints directly in VSCode
3. Debug!
=> Debug node backend in Docker from VSCode

twake/backend/core/app/Configuration/Commands.php, twake/backend/core/src/DevelopersApiV1/Messages/Controller/Message.php, twake/backend/core/src/Twake/Discussion/Command/NodePushChannelActivity.php, twake/backend/core/src/Twake/Discussion/Controller/Discussion.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/node/src/services/channels/services/channel/activities/index.ts, twake/backend/node/src/services/channels/services/channel/activities/service.ts, twake/backend/node/src/services/channels/services/channel/activities/types.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/index.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/channels/web/controllers/tab.ts, twake/backend/node/src/services/types/index.ts, twake/docker/twake-php/crontab, twake/frontend/src/app/components/Twacode/blocks/User.js, twake/frontend/src/app/scenes/Apps/Messages/Message/ActivityMessage.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/ui.scss
https://user-images.githubusercontent.com/36481167/107560895-315ca900-6bde-11eb-941e-2abab216ecda.mp4
https://user-images.githubusercontent.com/36481167/107560967-45080f80-6bde-11eb-8a7f-6792255d6390.mp4
=> #324 Log channel activities

twake/frontend/src/app/components/Inputs/InputWithSelect.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Header/MemberChannelRow.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
https://user-images.githubusercontent.com/36481167/107755878-ad143e00-6d23-11eb-89ec-8d39514ca62c.mp4
https://user-images.githubusercontent.com/36481167/107760362-e5b71600-6d29-11eb-8154-eee834403994.mp4
https://user-images.githubusercontent.com/36481167/107964757-e958d000-6fa9-11eb-8be1-7b2b360f1907.mp4
=> #916 Multiple bug fixes and improvements

twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/Channel.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/Channel.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx
https://user-images.githubusercontent.com/36481167/108050847-73f10c00-704a-11eb-8f9d-51e9d0889a8a.mp4
https://user-images.githubusercontent.com/36481167/108081365-2e940500-7071-11eb-82c3-978a1135049d.mp4
=> 🛠 #916 Multiple bug fixes and improvements again

twake/backend/node/src/core/platform/services/pubsub/amqp/client.ts
=> Catch error when trying to close a closed channel

twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/SearchListManager.ts, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/ChannelRow.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/DirectChannelRow.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/SearchListContainer.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/WorkspaceChannelRow.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
https://user-images.githubusercontent.com/36481167/109200282-b3cd9700-77a0-11eb-8ec4-b13dd70ca0f4.mp4
=> #311 Allow searching users and channels in CMD+K popup

LICENSE.md
Updated the License text based on the latest license document from Ludovic.
=> 📚 Update LICENSE.md 

twake/frontend/src/app/components/Banner/Banner.tsx, twake/frontend/src/app/components/NewVersion/NewVersionComponent.tsx, twake/frontend/src/app/components/ObjectModal/ObjectModal.scss, twake/frontend/src/app/components/ObjectModal/ObjectModal.tsx, twake/frontend/src/app/components/OnBoarding/AccountStatusComponent.tsx, twake/frontend/src/app/components/OnBoarding/popups/AddMailsInWorkspace.tsx, twake/frontend/src/app/components/OnBoarding/popups/BlockedAccount.tsx, twake/frontend/src/app/components/OnBoarding/popups/UnverifiedAccount.tsx, twake/frontend/src/app/components/OnBoarding/popups/VerifyEmail.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.tsx, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/theme.less
=> #969 Add onboarding new popups

twake/frontend/src/app/components/OnBoarding/popups/AddMailsInWorkspace.tsx, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUserFromTwakeConsole.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Pending.js, twake/frontend/src/app/services/ConsoleService.ts, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js
Preview:
https://user-images.githubusercontent.com/36481167/111494695-fb5f9700-873e-11eb-86d8-0bdc8718e15f.mp4
=> #969 Onboarding

twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Header/MemberChannelRow.tsx
https://user-images.githubusercontent.com/36481167/111616939-c9a00c00-87e2-11eb-9da8-2d0d00ab77d3.mp4
=> #1000 Close ChannelMember popup when user leave channel

twake/frontend/src/app/components/OnBoarding/CompanyStatusComponent.tsx, twake/frontend/src/app/components/OnBoarding/popups/AddMailsInWorkspace.tsx, twake/frontend/src/app/components/OnBoarding/popups/UnverifiedAccount.tsx, twake/frontend/src/app/components/OnBoarding/popups/WelcomeOnTwake.tsx, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUser.tsx, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUserFromTwakeConsole.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js, twake/frontend/src/app/services/ConsoleService.ts, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/workspaces/workspaces_users.js
https://user-images.githubusercontent.com/36481167/112156340-749b3600-8be6-11eb-8014-a493d1780a5e.mp4
https://user-images.githubusercontent.com/36481167/112159256-3d7a5400-8be9-11eb-890a-ecfb6d49a8bc.mp4
https://user-images.githubusercontent.com/36481167/112160382-65b68280-8bea-11eb-85e9-297c8b631fdd.mp4
https://user-images.githubusercontent.com/36481167/112176170-2858f180-8bf8-11eb-9056-7a0e383be119.mp4
=> 🎨 #1039 Improve UI and code on onboarding modals and headers

Contribute/HowtoApplyOurLicense.md
Please approve the merge request.
=> 📚 Create How to Apply Our License file.

twake/backend/core/src/Twake/Workspaces/Entity/Group.php, twake/backend/core/src/Twake/Workspaces/Entity/Workspace.php, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUserFromTwakeConsole.tsx, twake/frontend/src/app/services/workspaces/workspaces.js
=> 🩹 Release 434 patch

Contribute/Linagora Developer's Certificate of Origin
=> 🧑‍⚖️ Linagora Developer's Certificate of Origin [READY TO BE MERGED]

twake/frontend/src/app/app.tsx, twake/frontend/src/app/scenes/Apps/Drive/Drive.js, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/WorkspaceChannelList/WorkspaceChannelRow.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/DefaultChannelTab.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tab.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx, twake/frontend/src/app/scenes/Error/Error.tsx, twake/frontend/src/app/scenes/Error/ErrorBoundary.tsx, twake/frontend/src/app/scenes/Setup/Setup.tsx, twake/frontend/src/app/services/AppView/MainViewService.ts, twake/frontend/src/app/services/InitService.ts, twake/frontend/src/app/services/RouterService.ts, twake/frontend/src/app/services/channels/ChannelsBarService.ts, twake/frontend/src/app/services/channels/channels.js, twake/frontend/src/app/services/login/login.js, twake/frontend/src/app/services/user/notifications.tsx, twake/frontend/src/app/services/workspaces/workspaces.js
https://user-images.githubusercontent.com/36481167/111649265-7d65c380-8804-11eb-8d32-02b3038e71f7.mp4
=> ⬅️ #360 Fix Back / Next in browser

twake/backend/core/src/Twake/Calendar/Controller/Calendar.php, twake/backend/core/src/Twake/Calendar/Controller/Event.php, twake/backend/core/src/Twake/Discussion/Controller/Discussion.php, twake/backend/core/src/Twake/Drive/Controller/Download.php, twake/backend/core/src/Twake/Drive/Controller/DriveFile.php, twake/backend/core/src/Twake/Drive/Controller/Upload.php, twake/backend/core/src/Twake/Tasks/Controller/Board.php, twake/backend/core/src/Twake/Tasks/Controller/Task.php, twake/backend/core/src/Twake/Users/Services/User.php, twake/backend/core/src/Twake/Workspaces/Entity/Group.php, twake/backend/core/src/Twake/Workspaces/Entity/Workspace.php, twake/backend/node/src/core/platform/services/auth/web/jwt.ts, twake/backend/node/src/core/platform/services/tracker/index.ts, twake/backend/node/src/core/platform/services/types/index.ts, twake/backend/node/src/core/platform/services/websocket/services/index.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/types/index.ts, twake/frontend/src/app/scenes/Client/Popup/AddUser/AddUserFromTwakeConsole.tsx, twake/frontend/src/app/services/workspaces/workspaces.js
If console is used, we should use Console Identifier for main tracking tools id as requested by marketing teams.
=> 🛤 Tracker update

CONTRIBUTING.md
=> 🙌 Update Contributing.md

twake/backend/core/src/Twake/Core/Resources/views/Mail/de/inviteToWorkspaceMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/de/messages_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/de/subscribeMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/de/unread_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/en/inviteToWorkspaceMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/en/messages_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/en/subscribeMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/en/unread_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/fr/inviteToWorkspaceMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/fr/messages_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/fr/subscribeMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/fr/unread_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/ru/inviteToWorkspaceMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/ru/messages_notifications.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/ru/subscribeMail.html.twig, twake/backend/core/src/Twake/Core/Resources/views/Mail/ru/unread_notifications.html.twig, twake/backend/core/src/Twake/Core/Services/TwakeMailer.php, twake/backend/core/src/Twake/Users/Controller/UsersConnections.php, twake/backend/core/src/Twake/Users/Services/User.php, twake/backend/core/src/Twake/Users/Services/Users.php, twake/frontend/src/app/components/PopupComponent/PopupComponent.scss, twake/frontend/src/app/scenes/Apps/Calendar/FullCalendar/FullCalendar.js, twake/frontend/src/app/scenes/Apps/Drive/Drive.js, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/SearchListManager.ts, twake/frontend/src/app/services/Apps/Calendar/Calendar.js
Multiple minor fixes from QA and users.
#1086 
#1088 
#1091 
#1070 
CI and local run of Twake
Bug fix (non-breaking change which fixes an issue)
=> 🛠 Multiple fixes

twake/backend/core/src/Twake/Users/Controller/Adapters/Console/ApplyUpdates.php, twake/backend/core/src/Twake/Users/Controller/UsersConnections.php, twake/backend/core/src/Twake/Users/Entity/User.php, twake/backend/core/src/Twake/Users/Services/User.php, twake/backend/core/src/Twake/Workspaces/Entity/Group.php, twake/backend/core/src/Twake/Workspaces/Entity/Workspace.php, twake/backend/node/src/services/channels/entities/channel-activity.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/pubsub/new-channel-activity/index.ts, twake/backend/node/src/services/console/index.ts, twake/backend/node/src/services/console/processing/merge.ts, twake/backend/node/src/services/console/service.ts, twake/backend/node/src/services/console/types.ts, twake/backend/node/src/services/user/api.ts, twake/backend/node/src/services/user/entities/company.ts, twake/backend/node/src/services/user/entities/company_user.ts, twake/backend/node/src/services/user/entities/user.ts, twake/backend/node/src/services/user/services/external_links/index.ts, twake/backend/node/src/services/user/services/workspace/index.ts, twake/frontend/src/app/components/AddUserButton/AddUserButton.scss, twake/frontend/src/app/components/OnBoarding/popups/BlockedAccount.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/WorkspaceParameter.js, twake/frontend/src/app/services/ConsoleService.ts, twake/frontend/src/app/theme.less
~~Fixes #1145~~ -> Must be the code and not the id
=> 🛠 New fix for QA

twake/backend/core/src/Twake/Workspaces/Services/WorkspaceMembers.php, twake/frontend/src/app/components/Emojione/Emojione.scss, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/user/notifications.tsx
=> #1162 patch main

twake/frontend/src/app/services/Apps/Messages/MessageLoader.ts
=> Do not reset the top flag when coming back on a channel

twake/backend/core/src/Twake/Discussion/Entity/Message.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/Reactions.tsx
``` JSON
{
"id": "uuidv1",
"channel_id": "uuid",
"thread_id": "",
"created_at": number,
"type": "message"     // Classic message
| "event"   // Hidden events like key changes, or other system events
| "thread",  // Thread entry, content will be the head message content
"subtype": null
| "application" //Message from a connector
| "deleted" //Message deleted by user
| "system", // Message from system (channel activity)
"application_id": "uuid", //Additional information if message was sent by application
"user_id": "uuid", //Required
"edited": boolean,
"text": "string", // Original text typed by user and used in notifications
// It is parsed as markdown by frontend
// Most messages will only use this format
"blocks": [BlockObject], //Alternative nested json to replace text (if defined it …
```
=> 💬 #1189 Add new message object api

twake/backend/core/src/Twake/Users/Entity/User.php, twake/backend/node/src/cli/cmds/users.ts, twake/backend/node/src/cli/cmds/users_cmds/remove.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/services/user/entities/user.ts, twake/backend/node/src/services/user/services/users/service.ts, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/user/user.js
`docker-compose exec node ./bin/twake-cli users remove --id 62895cc6-8579-11eb-b52e-0242ac130003`
https://user-images.githubusercontent.com/36481167/116423801-4c37d480-a841-11eb-9bd2-02ecaf4100ca.mp4
=> 🗑 #1173 Add Ability to remove user account on Twake

twake/backend/node/src/services/channels/services/channel/service.ts
Ref to twake mobile issue [#507](https://github.com/linagora/Twake-Mobile/issues/507)
=> #twake-mobile-507 Fix last_message field in Channel

twake/frontend/package.json, twake/frontend/src/app/components/Twacode/Twacode.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/NewThread.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/AttachedFiles.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/InputAutocomplete.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/InputOptions.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageEdition.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/Options.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/TimeSeparator.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessageList.tsx, twake/frontend/src/app/scenes/Apps/Messages/Messages.scss, twake/frontend/src/app/scenes/Apps/Messages/Parts/Thread.tsx, twake/frontend/src/app/services/Apps/Messages/MessageEditorService.ts, twake/frontend/src/app/services/Apps/Messages/MessageEditorServiceFactory.ts, twake/frontend/src/app/services/Apps/Messages/MessageListService.ts, twake/frontend/src/app/services/Apps/Messages/MessageLoader.ts, twake/frontend/src/app/services/Apps/Messages/MessageLoaderFactory.ts, twake/frontend/src/app/services/Apps/Messages/Messages.js, twake/frontend/yarn.lock
=> Multiple message list fixes

twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsApps/ChannelsApps.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsUser/ChannelsUser.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsWorkspace/ChannelsWorkspace.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.tsx, twake/frontend/src/app/services/channels/ChannelCollectionPath.ts, twake/frontend/src/app/services/channels/ChannelsBarService.ts
Found this not so clean code while looking at the ChannelsCollection implementation. Took some minutes to clean.
💝
=> Cleanup ChannelsBarService

twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelMembersList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Header/MemberChannelRow.tsx, twake/frontend/src/app/services/GuestManagementService.ts
# Preview
https://user-images.githubusercontent.com/36481167/117162244-e6a89280-adc2-11eb-8878-7fbece1eda9f.mp4
=> #333 Fix Search in Guest Management popup and design improvements

twake/frontend/src/app/scenes/Apps/Messages/Messages.scss
Here it is, between 2 production updates...
=> #1269 Fix long thread display in sidebar

twake/start.sh
the initial command only copies the `default-configuration` directory into `configuration`.
This change aim to copy the default-configuration files into the configuration folder.
=> fix(start.sh): copy command

twake/backend/core/app/Configuration/Parameters.php.dist, twake/backend/core/src/Twake/Core/Command/TwakeSchemaUpdateCommand.php, twake/backend/core/src/Twake/Core/Controller/Version.php, twake/backend/core/src/Twake/Core/Services/DoctrineAdapter/DBAL/Driver/PDOCassandra/CassandraConnection.php, twake/frontend/src/app/components/OnBoarding/AccountStatusComponent.tsx, twake/frontend/src/app/models/Configuration.ts, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx
=> 🛠 Minor changes

twake/backend/node/src/services/user/web/controller.ts
fixed issue with invalidating cache (cache now it not instance dependent)
=> 🛠 Fixed company cache

twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/services/messages/services/engine/processors/channel-view/index.ts, twake/backend/node/src/services/messages/services/messages/service.ts, twake/backend/node/src/services/messages/services/messages/utils.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/notifications/services/engine/processors/new-channel-message/index.ts, twake/frontend/src/app/app.tsx, twake/frontend/src/app/services/Apps/Messages/Messages.js
=> 🛠 Messages node 1301b (more fixes)

twake/backend/node/src/cli/cmds/migration_cmds/php-message/message-migrator-service.ts
=> 🩹 #1230 Fix error: cannot find name 'workspace'

twake/backend/node/src/cli/cmds/migration_cmds/php-message/message-migrator-service.ts, twake/backend/node/src/services/console/processing/merge.ts, twake/backend/node/src/utils/workspace.ts
=> 🩹 #1230 Use workspace list method in message migrator service

twake/frontend/src/app/scenes/Client/WorkspacesBar/Components/Group.js, twake/frontend/src/app/services/languages/locale/en.js, twake/frontend/src/app/services/languages/locale/fr.js, twake/frontend/src/app/services/login/account.js, twake/frontend/src/app/services/login/login.js, twake/frontend/src/app/theme.less
https://user-images.githubusercontent.com/36481167/122935497-abf9ba00-d370-11eb-91aa-4d2978ede00b.mp4
=> 🛠 #1254 Small bug fixes

twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/frontend/src/app/scenes/Apps/Messages/MessageList.tsx, twake/frontend/src/app/services/Apps/Messages/Messages.js, twake/frontend/src/app/services/login/AuthProviderService.ts, twake/frontend/src/app/services/user/notifications.tsx
=> 🛠 QA Fixes

twake/backend/node/config/custom-environment-variables.json, twake/backend/node/config/default.json, twake/backend/node/config/test.json, twake/backend/node/src/core/platform/services/pubsub/amqp/index.ts, twake/backend/node/src/core/platform/services/pubsub/api.ts, twake/backend/node/src/core/platform/services/pubsub/factory.ts, twake/backend/node/src/core/platform/services/pubsub/index.ts, twake/backend/node/src/core/platform/services/pubsub/local/index.ts, twake/backend/node/src/core/platform/services/pubsub/proxy.ts
Implementation of pubsub using RXJS. The configuration has changed but defaults to AMQP implementation for now.
=> 🐰 Add RXJS local pubsub implementation

twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.scss, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx
https://user-images.githubusercontent.com/36481167/124257834-0d6a1780-db2d-11eb-8363-f59d9946e961.mp4
=> 🛠 #1379 Fix tab name ellipsis

twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/node/src/services/messages/services/engine/processors/message-to-notifications/index.ts, twake/backend/node/src/services/messages/services/messages/service.ts, twake/backend/node/src/services/messages/services/views/service.ts
=> 🩹 Main patch no 2

twake/backend/core/src/Twake/Discussion/Controller/Discussion.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/frontend/package.json, twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/models/Message.ts, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/MessageAndTimeSeparator.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/DeletedContent.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/FirstMessage/FirstMessage.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessageList.tsx, twake/frontend/src/app/scenes/Apps/Messages/Messages.tsx, twake/frontend/src/app/scenes/Apps/Messages/index.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/Channel.tsx, twake/frontend/src/app/scenes/Client/MainView/AppView/AppView.tsx, twake/frontend/src/app/scenes/Client/MainView/MainContent.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/DefaultChannelTab.tsx, twake/frontend/src/app/services/AppView/AppViewService.ts, twake/frontend/src/app/services/Apps/Messages/MessageHistoryService.ts, twake/frontend/src/app/services/Apps/Messages/MessageLoader.ts, twake/frontend/src/app/services/Apps/Messages/Messages.tsx, twake/frontend/yarn.lock
https://user-images.githubusercontent.com/36481167/124609730-2e55a400-de70-11eb-900c-cd16ba7e2e46.mp4
=> 🛠 #751 Fix side view and message improvements

twake/frontend/src/app/scenes/Apps/Messages/MessageList.tsx
=> #1171 Init thread message should not display replies in side view

twake/frontend/package.json, twake/frontend/src/app/components/RichTextEditor/Editor.tsx, twake/frontend/src/app/components/RichTextEditor/EditorDataParser.ts, twake/frontend/src/app/components/RichTextEditor/EditorStateService.ts, twake/frontend/src/app/components/RichTextEditor/EditorUtils.ts, twake/frontend/src/app/components/RichTextEditor/plugins/index.ts, twake/frontend/src/app/components/RichTextEditor/plugins/mentions/MentionSuggestion.tsx, twake/frontend/src/app/components/RichTextEditor/plugins/mentions/index.ts, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageEdition.tsx, twake/frontend/yarn.lock
=> Multiple Editor fixes

twake/frontend/src/app/components/RichTextEditor/Editor.scss, twake/frontend/src/app/components/RichTextEditor/Editor.tsx, twake/frontend/src/app/components/RichTextEditor/EditorUtils.ts, twake/frontend/src/app/components/RichTextEditor/plugins/suggestion/SuggestionList.scss, twake/frontend/src/app/components/RichTextEditor/plugins/suggestion/SuggestionList.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessageList.tsx, twake/frontend/src/app/scenes/Apps/Messages/Messages.scss, twake/frontend/src/app/services/hooks/useOnScreen.ts
Fixes
- #1462
- #1478  
Also updated how the `Scroll to bottom` button should behave.
=> 🛠 Message editor improvements

twake/frontend/public/locales/de.json, twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.tsx
=> 🛠  #1475 Move Add user button under direct messages list

twake/frontend/src/app/components/RichTextEditor/Editor.tsx, twake/frontend/src/app/components/RichTextEditor/EditorDataParser.ts, twake/frontend/src/app/components/RichTextEditor/markdown/README.md, twake/frontend/src/app/components/RichTextEditor/markdown/draft-to-markdown.js, twake/frontend/src/app/components/RichTextEditor/markdown/types.ts, twake/frontend/src/app/components/RichTextEditor/plugins/index.ts, twake/frontend/src/app/components/RichTextEditor/plugins/mentions/index.ts, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx
=> 🛠 Editor blocks fixes

twake/frontend/src/app/components/RichTextEditor/Editor.tsx, twake/frontend/src/app/components/RichTextEditor/TextCount/TextCount.scss, twake/frontend/src/app/components/RichTextEditor/TextCount/TextCount.tsx, twake/frontend/src/app/components/RichTextEditor/TextCount/TextCountService.ts, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.scss, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Parts/InputOptions.tsx, twake/frontend/src/app/theme.less
Should work better, also improved performance by computing text length once when needed and moved component at the right place.
Fix #1440
=> Improve message length limitation

twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx
https://user-images.githubusercontent.com/36481167/127659675-52b1b242-4920-437f-ab1a-c3fdec6a459b.mp4
=> #1508 Fix setUploadZoneRef in Input.tsx

twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/components/Uploads/UploadZone.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx
https://user-images.githubusercontent.com/36481167/127870249-26a1b49a-aa8c-418f-8092-d82b10689937.mp4
=> #1242 Limit upload according to the attachements limit

twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/components/Calendar/Event/Event.js, twake/frontend/src/app/components/EmojiPicker/EmojiPicker.js, twake/frontend/src/app/components/EmojiPicker/EmojiPicker.scss, twake/frontend/src/app/scenes/Apps/Calendar/FullCalendar/FullCalendar.js, twake/frontend/src/app/scenes/Apps/Calendar/Modals/EventDetails.js, twake/frontend/src/app/scenes/Apps/Drive/Drive.js
https://user-images.githubusercontent.com/36481167/127889615-5abfe872-a797-4b41-ab56-279a03eb6f4f.mp4
=> #1240 Add missing translations

twake/frontend/src/app/components/Menus/MenuComponent.js, twake/frontend/src/app/components/Menus/MenusBodyLayer.js, twake/frontend/src/app/components/Menus/MenusManager.js, twake/frontend/src/app/components/RichTextEditor/Editor.scss, twake/frontend/src/app/scenes/Client/Client.scss, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/MainContent.tsx, twake/frontend/src/app/scenes/Client/MainView/MainHeader/ChannelHeader/ChannelHeader.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.scss, twake/frontend/src/app/scenes/Client/MainView/MainView.tsx
=> 📱 Fix web mobile view 

twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/backend/node/src/services/workspaces/web/controllers/workspaces.ts, twake/backend/node/src/utils/company.ts, twake/backend/node/src/utils/workspace.ts, twake/backend/node/test/e2e/workspaces/workspaces.spec.ts, twake/backend/node/test/http/workspaces.http
https://user-images.githubusercontent.com/36481167/128373039-070fb4c5-4648-4949-a0e2-b2d1089b20fc.mp4
=> #156 Fix Twake allows duplicate workspaces

twake/frontend/src/app/scenes/Client/MainView/MainView.scss, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx
https://user-images.githubusercontent.com/36481167/128524729-60babefb-ad05-4473-8bb3-3dcea8e1eced.mp4
=> #1502 Fix tabs wrapping and scrolling

twake/frontend/src/app/components/RichTextEditor/plugins/emoji/index.ts
=> #1549 Do not add suggestion to the list when emoji suggestion is undefined

twake/backend/core/src/Twake/Drive/Services/DriveFileSystem.php
=> 🛠  Fix #1630

twake/backend/core/src/Twake/Workspaces/Services/WorkspaceMembers.php
=> 🛠 Guest fix php side

.github/workflows/labels.yml
https://www.notion.so/twake/ADR-WIP-Release-workflow-d58c8c80964d4530bd7480ff40bd0871
This PR will not implement main cherry-picking and be used only for testing other environments first.
=> 🤖  Implement new automated workflow auto-labeling and cherry-picking (except for main)

twake/backend/node/src/services/console/clients/remote.ts, twake/frontend/src/app/scenes/Client/Popup/CreateCompanyView/CreateCompanyView.js, twake/frontend/src/app/scenes/Client/Popup/CreateWorkspacePage/CreateWorkspacePage.js, twake/frontend/src/app/services/Console/ConsoleService.ts, twake/frontend/src/app/services/GuestMember/GuestManagementService.ts, twake/frontend/src/app/services/workspaces/workspaces.js
=> 🛠  Fix unhandled console invitation call

.github/workflows/labels.yml
=> 🤖 Fix auto-label when merge

.github/workflows/labels.yml, twake/backend/node/package.json, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/console/clients/remote.ts, twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json
=> 🛠 Fix mobile issues and deployment workflow

.github/workflows/labels.yml
https://github.com/actions/checkout
=> 🤖 Workflow bot add fetch-depth

twake/backend/node/package-lock.json, twake/backend/node/package.json, twake/backend/node/src/services/console/clients/remote.ts, twake/frontend/public/.well-known/apple-app-site-association, twake/frontend/public/.well-known/assetlinks.json, twake/frontend/public/index.html, twake/frontend/src/app/components/ScrollHiddenComponents/HiddenNotificationService.ts
=> 📱 Mobile deep link and fixes 01102021

twake/backend/node/test/e2e/notifications/mention.spec.ts
=> 🛠 Fix mention tests

twake/frontend/src/app/components/Inputs/InputWithIcon.tsx, twake/frontend/src/app/scenes/Apps/Tasks/Board/BoardEditor.js, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelTemplateEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CurrentUser.js
ref to #1557
https://user-images.githubusercontent.com/36481167/142399100-ad392fc5-2f13-43e2-a712-c4ef5e1bf712.mp4
=> #1557 InputWithIcon to typescript and fix onPressEnter props

twake/backend/node/src/cli/cmds/export_cmds/export_company.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/service.ts
=> 🔎 Improve export nov2021 #1767

twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/Workspace/WorkspaceIdentity.tsx, twake/frontend/src/app/services/utils/URLUtils.ts, twake/frontend/src/app/services/workspaces/WorkspaceAPIClient.ts, twake/frontend/src/app/state/recoil/hooks/useCurrentWorkspace.ts
https://user-images.githubusercontent.com/36481167/143607023-57d6efec-120a-4351-ab6c-8159dd76da7e.mp4
=> 🛠 #1756 Improve Workspace identity component

twake/backend/node/src/core/platform/services/counter/provider.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/mongodb.ts, twake/backend/node/src/services/channels/entities/channel.ts, twake/backend/node/src/services/channels/entities/channel_counters.ts, twake/backend/node/src/services/channels/index.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/index.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/channel/types.ts, twake/backend/node/src/services/channels/services/index.ts, twake/backend/node/src/services/channels/services/member/index.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/channels/web/schemas.ts, twake/backend/node/src/services/user/api.ts, twake/backend/node/src/services/user/services/companies/service.ts, twake/backend/node/test/e2e/channels/channels.rest.spec.ts, twake/backend/node/test/e2e/channels/utils.ts, twake/backend/node/test/e2e/utils.prepare.db.ts
=> 🌟 Channel counters for members and guests

twake/backend/core/src/Twake/Drive/Services/DriveFileSystem.php
- Fix an error while uploading file in the depreciated php api
=> 🛠 Fix DriveFile error on upload

twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/MenuCompanyHeader.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/Components/CompanySelector/index.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/Components/CompanySelector/styles.scss, twake/frontend/src/app/scenes/Client/WorkspacesBar/WorkspacesBar.scss, twake/frontend/src/app/scenes/Client/WorkspacesBar/WorkspacesBar.tsx
https://user-images.githubusercontent.com/36481167/145798474-351634bf-202a-4771-9ced-ee992a166f44.mp4
=> 🛠 #1790 Fix auto-generated company logo does not look nice

twake/backend/node/config/default.json, twake/backend/node/src/services/applications/index.ts, twake/backend/node/src/services/console/clients/remote.ts, twake/backend/node/src/services/console/types.ts, twake/frontend/src/app/models/User.ts, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/WorkspaceParameter.js, twake/frontend/src/app/services/Application.ts, twake/frontend/src/app/services/Realtime/useRealtime.ts, twake/frontend/src/app/services/user/UserAPIClient.ts, twake/frontend/src/app/state/recoil/hooks/useCompanies.ts, twake/frontend/src/app/state/recoil/hooks/useCurrentUser.ts
=> 🛠 General fixes qa 16122021

twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/Channel.tsx
https://user-images.githubusercontent.com/36481167/146528174-523880fd-0c64-48a2-893e-026b8d68816b.mp4
=> #1833 Use the react feather icons for the application logos in the sidebar

twake/frontend/src/app/components/UserListManager/UserListManager.tsx
https://user-images.githubusercontent.com/36481167/147080833-8f109b9e-ce2f-4c65-b6c8-d8ca701277d7.mp4
=> #1842 Fix UserListManager

twake/frontend/src/app/components/ui/UserOrMail.tsx, twake/frontend/src/app/services/CompanyAPIClient.ts, twake/frontend/src/app/state/recoil/hooks/useCompanies.ts
https://user-images.githubusercontent.com/36481167/147086301-dd4a716f-777b-4093-9a13-3f12066c7371.mp4
=> #1844 Fix calendar event creation

twake/backend/node/src/cli/cmds/migration_cmds/application.ts, twake/frontend/src/app/components/File/FileComponent.tsx, twake/frontend/src/app/components/Twacode/PseudoMarkdownDictionary.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/DefaultChannelTab.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/Applications/CompanyApplicationsTable.tsx
- Old messages drive files display
=> 🛠 Production patch

twake/backend/node/src/services/workspaces/web/controllers/workspaces.ts, twake/frontend/src/app/components/Inputs/InputWithIcon.tsx, twake/frontend/src/app/scenes/Apps/Drive/Viewer/Viewer.scss, twake/frontend/src/app/scenes/Apps/Drive/Viewer/Viewer.tsx, twake/frontend/src/app/scenes/Apps/Tasks/Tasks.scss, twake/frontend/src/app/services/Apps/Messages/clients/MessageAPIClient.ts, twake/frontend/src/app/services/Apps/Messages/clients/MessageViewAPIClient.ts
✅ Invisibles messages on mobile
✅ Workspace level set to guest when should be member
✅ Drive header UI broken
✅ Tasks add board broken
=> 🩹Patch end of december 2021

twake/frontend/src/app/scenes/Apps/Calendar/CalendarContent.js, twake/frontend/src/app/scenes/Apps/Calendar/UnconfiguredTab.js, twake/frontend/src/app/scenes/Apps/Tasks/Tasks.tsx, twake/frontend/src/app/scenes/Apps/Tasks/UnconfiguredTab.js, twake/frontend/src/app/scenes/Client/MainView/AppView/AppView.tsx
Fix a bug with changing month on calendar
=> 🛠 Fix calendar change month issue

twake/backend/node/src/core/platform/services/pubsub/api.ts, twake/backend/node/src/services/workspaces/web/routes.ts, twake/backend/node/test/e2e/workspaces/workspace-pending-users.spec.ts, twake/frontend/src/app/models/Message.ts, twake/frontend/src/app/models/User.ts, twake/frontend/src/app/scenes/Apps/Messages/ListBuilder.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/ThreadAvatar.tsx, twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Pending.tsx, twake/frontend/src/app/services/user/UserService.ts, twake/frontend/src/app/state/recoil/atoms/CompanyApplications.ts, twake/frontend/src/app/state/recoil/hooks/useCompanyApplications.ts
- rmq error
- perf
- user avatars
=> 🩹 Patch January 3, 2022

twake/frontend/public/locales/en.json, twake/frontend/public/locales/es.json, twake/frontend/public/locales/fr.json, twake/frontend/public/locales/ru.json, twake/frontend/src/app/components/RichTextEditor/Editor.tsx, twake/frontend/src/app/components/RichTextEditor/EditorToolbar.scss, twake/frontend/src/app/components/RichTextEditor/EditorUtils.ts, twake/frontend/src/app/components/RichTextEditor/plugins/suggestion/SuggestionList.tsx, twake/frontend/src/app/components/RichTextEditor/plugins/suggestion/utils.ts
#1615
https://user-images.githubusercontent.com/36481167/147256391-410ba808-beef-47ab-85e5-168f42ab3e5b.mp4
=> 🛠 #1615 Fix input issues

twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx, twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx, twake/frontend/src/app/scenes/Apps/Messages/Parts/ThreadAvatar.tsx, twake/frontend/src/app/services/Application.ts, twake/frontend/src/app/services/Collections/Transport/TransportAPI.ts, twake/frontend/src/app/services/Collections/Transport/TransportHTTP.ts, twake/frontend/src/app/services/JWTStorage.ts, twake/frontend/src/app/services/Twacode/pseudoMarkdownCompiler.ts
- rmq error
- perf
- user avatars
- messages feed perf
- auto renew jwt
=> 🩹Patch 2 of January B

twake/backend/node/src/services/channels/services/pubsub/new-workspace/index.ts, twake/frontend/public/locales/en.json, twake/frontend/src/app/components/RichTextEditor/TextCount/TextCount.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Apps/Messages/ListBuilder.tsx, twake/frontend/src/app/scenes/Apps/Messages/MessagesList.tsx, twake/frontend/src/app/scenes/Apps/Messages/ThreadMessagesList.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Login/Internal/Signin/Signin.js, twake/frontend/src/app/services/FeatureTogglesService.ts, twake/frontend/src/app/services/JWTStorage.ts, twake/frontend/src/app/services/login/LoginService.ts, twake/frontend/src/app/state/recoil/atoms/Companies.ts, twake/frontend/src/app/state/recoil/hooks/messages/useChannelMessages.ts, twake/frontend/src/app/state/recoil/hooks/messages/useThreadMessages.ts, twake/frontend/src/app/state/recoil/hooks/messages/windows.ts, twake/frontend/src/app/state/recoil/hooks/useCompanies.ts
- Only logout if renew failed and server is reachable
- Load the feature toggle at the right position
- Fix sign up not ending in onpremise
- Fix useCompany calling 404 urls
=> 🩹 Patch 05-01-2022

twake/backend/node/src/core/platform/framework/logger.ts
=> #1826 Fix cannot read properties of undefined in backend

twake/backend/node/src/core/platform/services/counter/provider.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/typeTransforms.ts, twake/backend/node/src/core/platform/services/webserver/index.ts, twake/backend/node/src/services/channels/services/channel/types.ts, twake/backend/node/src/services/channels/services/pubsub/index.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/channels/web/schemas.ts, twake/backend/node/src/services/online/constants.ts, twake/backend/node/src/services/online/index.ts, twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-users.ts, twake/backend/node/src/services/workspaces/web/controllers/workspaces.ts, twake/backend/node/src/services/workspaces/web/routes.ts, twake/backend/node/src/services/workspaces/web/schemas.ts, twake/backend/node/src/utils/workspace.ts, twake/backend/node/test/e2e/channels/channels.rest.spec.ts, twake/backend/node/test/e2e/counters.spec.ts, twake/backend/node/test/e2e/run-all.js, twake/backend/node/test/e2e/workspaces/workspace-users.spec.ts, twake/docker-compose.dev.tests.mongo.yml, twake/frontend/src/app/components/Configurators/ConfigBodyLayer.js, twake/frontend/src/app/scenes/Apps/Drive/Viewer/Viewer.tsx, twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx
=> 🛠 Fix guest popup not openning + right issue

twake/backend/node/src/services/workspaces/services/workspace/service.ts
Replace non url-friendly chars: +/= to ._-
=> 🛠 Fix characters of magic links

twake/backend/node/src/services/workspaces/entities/workspace_user.ts, twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-invite-tokens.ts
Duplicate of #1942 for canary version
=> 🛠 Fix magic links on canary version

twake/frontend/src/app/views/client/workspaces-bar/styles.scss
https://user-images.githubusercontent.com/36481167/154242261-17bb9aa4-2fd7-4893-b8e9-9a54ac025b9e.mp4
=> #1493 Hide scrollbar while hovering the workspace side bar

twake/backend/node/src/services/console/processing/merge.ts, twake/backend/node/src/services/console/types.ts, twake/backend/node/src/services/workspaces/api.ts, twake/backend/node/src/services/workspaces/entities/workspace_invite_tokens.ts, twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-invite-tokens.ts, twake/backend/node/src/services/workspaces/web/types.ts, twake/backend/node/test/e2e/workspaces/workspaces.invite-tokens.spec.ts, twake/frontend/src/app/state/recoil/hooks/channels/usePublicOrPrivateChannels.ts
=> 🛠 Fix canary 1802

twake/backend/node/src/services/user/utils.ts, twake/frontend/src/app/views/client/workspaces-bar/components/NoWorkspaces/GotALink.tsx, twake/frontend/src/app/views/client/workspaces-bar/components/NoWorkspaces/NoCompanies.tsx, twake/frontend/src/app/views/client/workspaces-bar/components/NoWorkspaces/NoWorkspaces.tsx, twake/frontend/src/app/views/join/index.tsx, twake/frontend/src/app/views/join/styles.scss
=> 🛠 Multiple QA fixes

twake/backend/node/src/core/platform/services/search/adapters/elasticsearch/index.ts, twake/backend/node/src/services/console/clients/remote.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-invite-tokens.ts, twake/frontend/public/locales/en.json, twake/frontend/src/app/components/locked-features-components/feature-toggles-hooks.tsx, twake/frontend/src/app/components/locked-features-components/locked-invite-alert/index.tsx, twake/frontend/src/app/features/auth/provider/oidc/oidc-auth-provider-service.ts, twake/frontend/src/app/features/global/services/feature-toggles-service.ts, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartner.tsx, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Members.tsx, twake/frontend/src/app/views/join/index.tsx
Fix magic link and user invite limit notice
=> Improve company members limit

changelog.md, twake/backend/node/src/core/platform/services/storage/connectors/S3/service.ts, twake/backend/node/src/services/files/services/index.ts, twake/docker/twake-nginx/site.conf, twake/frontend/public/.well-known/assetlinks.json, twake/frontend/src/app/components/file/file-component.tsx, twake/frontend/src/app/components/file/file.scss, twake/frontend/src/app/components/file/types.ts, twake/frontend/src/app/components/popup-component/popup-component.scss, twake/frontend/src/app/components/twacode/blocks/user.tsx, twake/frontend/src/app/features/global/utils/managedSearchRequest.ts, twake/frontend/src/app/features/users/hooks/use-user.ts, twake/frontend/src/app/features/users/state/selectors/user-selector.ts, twake/frontend/src/app/views/applications/messages/input/parts/IsWriting.tsx, twake/frontend/src/app/views/applications/messages/list-builder.tsx, twake/frontend/src/app/views/applications/messages/message/parts/Blocks.tsx, twake/frontend/src/app/views/applications/messages/message/parts/Blocks.utils.ts, twake/frontend/src/app/views/applications/messages/message/parts/MessageAttachments.tsx, twake/frontend/src/app/views/applications/messages/message/parts/PossiblyPendingAttachment.tsx, twake/frontend/src/app/views/applications/messages/messages.scss, twake/frontend/src/app/views/client/channels-bar/Parts/CurrentUser/CurrentUser.js, twake/frontend/src/app/views/client/index.tsx, twake/frontend/src/app/views/client/popup/AppsParameters/AppsParameters.scss, twake/frontend/src/app/views/client/popup/UserParameter/UserParameter.scss, twake/frontend/src/app/views/client/popup/WorkspaceParameter/WorkspaceParameter.scss, twake/frontend/src/app/views/client/workspaces-bar/components/NoWorkspaces/styles.scss, twake/frontend/yarn.lock
=> 🌟 Cool improvements and last minute fixes

twake/frontend/src/app/components/popup-component/popup-component.scss
=> #2022 Fix popup content height

twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/messages/services/messages/service.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/views.ts, twake/backend/node/test/e2e/messages/messages.views.channel.spec.ts
Now ?flat=1 requests works with include_users
=> 🛠 Fix include users

twake/backend/node/src/services/workspaces/web/controllers/workspaces.ts
Update workspace name was reseting the logo
Fixed
=> 🛠 fix getting config for console

twake/backend/node/src/services/messages/blocks-types.ts, twake/frontend/src/app/components/twacode/blocksCompiler.ts, twake/frontend/src/app/views/applications/messages/message/parts/Blocks.tsx
Creating a block compiler to be able to use Slacks block and compile the block into Twacode to use it in Twake 
https://github.com/linagora/Twake/issues/2071 : Build blocks<->twacode converter
=> 🌟 2071: Create BlockCompiler + update blocks-type and use block compiler

twake/frontend/src/app/components/calendar/event/event.js, twake/frontend/src/app/components/user-list-manager-depreciated/elements.scss, twake/frontend/src/app/components/user-list-manager-depreciated/user-list-manager.scss, twake/frontend/src/app/components/user-list-manager-depreciated/user-list-manager.tsx, twake/frontend/src/app/views/applications/calendar/modals/Part/Participants.js
Priority one to production if tests pass
=> 🛠 Fix broken calendar

twake/backend/node/src/core/platform/services/pubsub/api.ts, twake/backend/node/src/core/platform/services/pubsub/processor.ts
It was a out of order initialisation of the pubsub
=> 🛠 Fix amqp not working global resolver

twake/backend/node/src/services/console/clients/remote.ts, twake/backend/node/src/services/console/types.ts, twake/backend/node/src/services/console/web/controller.ts, twake/backend/node/src/services/user/api.ts, twake/backend/node/src/services/user/entities/company_user.ts, twake/backend/node/src/services/user/services/companies.ts, twake/backend/node/test/e2e/console/console-hooks.spec.ts
=> 🌟 Prepare console merge

twake/frontend/src/app/components/search-popup/parts/messages-result.tsx, twake/frontend/src/app/features/global/utils/strings.ts
=> 🛠 Fix multiple canary issues

twake/backend/node/package-lock.json, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/channel/types.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/user/web/controller.ts, twake/backend/node/src/services/user/web/routes.ts, twake/backend/node/test/e2e/users/users.spec.ts, twake/backend/node/yarn.lock, twake/docker-compose.dev.tests.mongo.yml
https://app.zenhub.com/workspaces/twake-5f06c5bf7796310019354875/issues/linagora/twake/2165
#2165
=> 🌟 recent contacts

twake/backend/node/src/services/channels/web/controllers/channel.ts
=> 🛠 fix limit

twake/backend/core/src/Twake/Market/Services/ApplicationApi.php, twake/frontend/src/app/components/company-messages-counter/company-messages-counter.tsx, twake/frontend/src/app/components/locked-features-components/locked-drive-popup/locked-drive-popup.tsx, twake/frontend/src/app/components/locked-features-components/locked-history-banner/locked-history-banner.tsx, twake/frontend/src/app/components/locked-features-components/locked-invite-alert/index.tsx, twake/frontend/src/app/components/locked-features-components/locked-only-office-popup/locked-only-office-popup.tsx, twake/frontend/src/app/components/locked-features-components/locked-workspace-popup/locked-workspace-popup.tsx, twake/frontend/src/app/components/on-boarding/company-billing-banner.tsx, twake/frontend/src/app/components/on-boarding/popups/blocked-company.tsx, twake/frontend/src/app/features/console/services/console-service.ts, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelMenu.tsx
=> 🛠 Fix api and sub link

twake/backend/node/src/services/messages/services/messages.ts, twake/frontend/src/app/components/twacode/twacode.tsx, twake/frontend/src/app/features/channels/api/channel-api-client.ts, twake/frontend/src/app/features/users/hooks/use-notifications.ts, twake/frontend/src/app/views/applications/messages/input/parts/EphemeralMessages.tsx, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx, twake/frontend/src/app/views/applications/messages/messages-list.tsx, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelMenu.tsx
Fix
- #2136
- #2194
- #2195 
- #2187 
- #2199
=> Fix #2136 #2194 #2195 #2187 #2199

twake/backend/node/src/services/messages/services/views.ts
Filter done at the wrong place.
=> 🛠  Fix typo with recent files

twake/backend/node/config/default.json, twake/backend/node/src/services/console/clients/remote.ts, twake/backend/node/src/services/console/service.ts, twake/backend/node/src/services/console/types.ts, twake/backend/node/src/services/messages/api.ts, twake/backend/node/src/services/messages/services/views.ts, twake/backend/node/src/services/messages/web/controllers/views.ts, twake/backend/node/src/services/messages/web/controllers/views/recent-files.ts, twake/backend/node/src/services/messages/web/controllers/views/search-files.ts, twake/backend/node/src/services/previews/services/files/processing/mime.ts, twake/backend/node/test/e2e/messages/messages.files.spec.ts, twake/frontend/src/app/components/twacode/pseudo-markdown-dictionary.tsx, twake/frontend/src/app/views/applications/messages/message/parts/Blocks.tsx, twake/frontend/src/app/views/client/main-view/PublicMainView.js, twake/frontend/src/app/views/client/popup/application-parameters/pages/WorkspaceAppsEditor.js, twake/frontend/src/app/views/integration/components/apps.js, twake/frontend/src/app/views/login/internal/signin/signin.js
- Fix #2237
- Fix #2196 
- Fix email pattern not accepted in on-premise
- Add pagination to files and messages search
- Empty file search returns recent files
- Fix Console breaking changes
=> 🛠 Multiple fixes June 8

twake/frontend/src/app/views/client/channels-bar/Parts/Footer/Footer.js
- Add version detail in the Help tab
#2055 
Quick view to see the current Version displayed directly in help menu.
- Add a flag to be able to test in local
=> 🌟 Add version detail in the Help tab

twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/features/global/utils/CopyClipboard.ts, twake/frontend/src/app/views/applications/messages/message/parts/Options.tsx, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelMenu.tsx
Be able to copy a public channel link to clipboard 
#2029
=> :star2: Add channel share link

twake/frontend/src/app/features/users/hooks/use-search-user-list.ts, twake/frontend/src/app/views/client/channels-bar/ChannelsUser/ChannelsUser.tsx, twake/frontend/src/app/views/client/channels-bar/Modals/new-direct-channel-popup/index.tsx, twake/frontend/src/app/views/client/channels-bar/Modals/new-direct-channel-popup/select-users.tsx, twake/frontend/src/app/views/client/channels-bar/Modals/new-direct-channel-popup/style.scss
Related to #2277 
https://user-images.githubusercontent.com/14353924/173331447-0d08bb5d-6987-4ade-ae76-5ac0556eb563.mp4
=> 🌟 Brand new direct chat creation popup

twake/backend/node/src/services/workspaces/services/workspace.ts, twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/Workspace/WorkspaceIdentity.tsx
#1519 
Give feedback to the user when update successful done
localy
* Fix delete logo button 
https://user-images.githubusercontent.com/7097550/173547408-c1a10b5b-61d6-4208-94d3-ec3ef1dd0826.mp4
* Fix delete logo button
https://user-images.githubusercontent.com/7097550/173606386-d22585df-6e44-4395-a1c3-6d214df1a25f.mp4
=> 🛠  Fix notification message when updating workspace infos

twake/frontend/public/styles/tailwind.css, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.scss, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.tsx
- changed the link preview component style to make it responsive
#2303 
- fixes the link preview not being responsive for mobile devices.
- locally
https://user-images.githubusercontent.com/6764881/174085661-d0adb45e-01d1-4bf8-93d2-2ef6d0dcd086.mp4
=> 🛠 Fixed link preview not being responsive for mobile

twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/files/entities/file.ts, twake/backend/node/src/services/files/utils.ts, twake/backend/node/src/services/files/web/routes.ts, twake/backend/node/src/services/messages/utils.ts, twake/backend/node/src/services/messages/web/controllers/views/search-files.ts, twake/backend/node/test/e2e/channels/channels.rest.spec.ts
[Fix](https://github.com/linagora/Twake/commit/5119372febc1d4c9f6a3aa1ac1f3051e48c02906) https://github.com/linagora/Twake/issues/2296
[Fix](https://github.com/linagora/Twake/commit/53d4c2a55a424992c90fdce2f93bad1c51dc7bcc) https://github.com/linagora/Twake/issues/2289
[Fix](https://github.com/linagora/Twake/commit/4f7fd15e9cd9079bb2b92702b9dcf8e423ece629) https://github.com/linagora/Twake/issues/2309
=> 🛠 Multiple search related fixes

twake/frontend/.storybook/preview.js, twake/frontend/public/styles/tailwind.css, twake/frontend/src/app/molecules/tabs/index.stories.tsx, twake/frontend/src/app/molecules/tabs/index.tsx
https://user-images.githubusercontent.com/1404610/175328878-f4f049b0-5a15-4ecd-b3d4-cd5894e42431.mov
=> 👨‍💻 molecule/tabs

twake/frontend/src/app/features/console/services/console-service.ts
The new merged console does not allow members to invite, so we'll complete the error message temporarily until being fixed
=> 🛠 Fix merge console invite right

twake/frontend/src/app/views/applications/messages/list-builder.tsx, twake/frontend/src/app/views/applications/messages/messages-list.tsx, twake/frontend/src/app/views/applications/messages/thread-messages-list.tsx
=> 🛠 Fix infinite calls when scrolling down

twake/backend/node/src/cli/cmds/migration_cmds/messages-files-medias-separation.ts, twake/backend/node/src/core/platform/services/search/adapters/elasticsearch/search.ts, twake/backend/node/src/core/platform/services/search/api.ts, twake/backend/node/src/services/files/utils.ts, twake/backend/node/src/services/messages/entities/message-file-refs.ts, twake/backend/node/src/services/messages/entities/message-files.search.ts, twake/backend/node/src/services/messages/entities/messages.search.ts, twake/backend/node/src/services/messages/services/engine/processors/files/index.ts, twake/backend/node/src/services/messages/services/views.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/views/search-files.ts, twake/frontend/src/app/features/users/hooks/use-notifications.ts, twake/frontend/src/app/features/users/services/push-desktop-notification.tsx, twake/frontend/src/app/views/desktop-redirect/index.tsx
=> 🛠 Work unit 5

twake/backend/node/package.json, twake/backend/node/src/services/files/web/controllers/files.ts, twake/backend/node/src/services/files/web/index.ts, twake/backend/node/src/services/previews/services/files/processing/video.ts, twake/backend/node/test/unit/services/previews/services/files/processing/video.test.ts, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.tsx
- improved link preview to use the maximum height and width of found image
- added a cache-control header for thumbnail files
- changed video preview generation to use JPG images instead of PNG ( better compression, less size )
- general improvements to video, link previews and thumbnail caching
- locally
- ![image](https://user-images.githubusercontent.com/6764881/178073375-ca2ea2f9-a672-4780-994b-6887c6288a58.png)
- ![image](https://user-images.githubusercontent.com/6764881/178073838-a92d6a0b-afb1-44ae-b239-42a93290556b.png)
- ![image](https://user-images.githubusercontent.com/6764881/178074038-d3eabe0e-2232-449c-84d9-eab0e2e677ee.png)
=> preview improvement

twake/backend/node/src/services/messages/entities/message-files.ts, twake/backend/node/src/services/messages/services/messages-files.ts, twake/backend/node/src/services/messages/services/views.ts, twake/backend/node/src/services/messages/web/controllers/messages-files.ts, twake/backend/node/src/services/messages/web/controllers/views/recent-files.ts, twake/backend/node/src/services/messages/web/controllers/views/search-files.ts, twake/frontend/src/app/features/global/services/languages-service.ts
=> 🛠 Fix pagination for message files

twake/backend/node/src/services/messages/services/views.ts
=> 🛠 Pagination for files and more

twake/frontend/public/locales/en.json, twake/frontend/src/app/components/channel-attachement-list/channel-attachement-list.tsx, twake/frontend/src/app/components/channel-attachement-list/parts/channel-attachment.tsx, twake/frontend/src/app/components/channel-attachement-list/parts/channel-files.tsx, twake/frontend/src/app/components/channel-attachement-list/parts/channel-medias.tsx, twake/frontend/src/app/components/channel-attachement-list/parts/commun.tsx, twake/frontend/src/app/features/channels/hooks/use-channel-media-files.ts, twake/frontend/src/app/features/channels/state/channel-attachment-list.ts, twake/frontend/src/app/features/messages/api/message-api-client.ts, twake/frontend/src/app/views/client/index.tsx, twake/frontend/src/app/views/client/main-view/MainHeader/ChannelHeader/ChannelHeader.tsx
- added channel medias and files view
- changed the participants button with icons for info, medias, and participants
#2403 
- adds the ability to quickly look for medias and files of the current channel
- locally
https://user-images.githubusercontent.com/6764881/178776195-bac86535-5ae2-41f5-9973-7fbfddef0e82.mp4
https://user-images.githubusercontent.com/6764881/178776216-1715f1cc-181f-415d-8cb0-fa6cf08a90e8.mp4
=> 🌟 Added channel files and medias view

twake/frontend/src/app/views/applications/messages/message/parts/Blocks.utils.ts, twake/frontend/src/tailwind.css
- Fixed code block not showing up properly
- Fixed quote block not showing up
- Fixed ordered list being removed by tailwind.css
#2447 
- fixes message display issues
- locally
=> 🛠  Fixed code, quote, ordered list blocks not showing up

twake/backend/node/package.json, twake/backend/node/src/@types/emoji-name-map.ts, twake/backend/node/src/services/messages/services/engine/index.ts, twake/backend/node/src/services/messages/services/messages-operations.ts, twake/backend/node/src/services/notifications/services/engine/index.ts, twake/backend/node/src/services/notifications/services/engine/processors/reaction-notification.ts, twake/backend/node/src/services/notifications/types.ts
Add push notification when someone react to a message
#2414
=> 🌟 Add push reaction notification

twake/backend/node/src/services/messages/services/messages.ts
Add the users in the quoted messages
#2461
=> 🛠 Add user to quoted message

twake/frontend/src/app/components/channel-attachement-list/parts/commun.tsx
- removed a rogue semicolon being visible when loading 
#2459 
- fixes a UI bug
- locally
=> 🛠️  fixed semicolon being visible when loading in channel medias and files view

twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/messages/web/controllers/messages.ts, twake/backend/node/src/services/messages/web/routes.ts, twake/backend/node/src/utils/messages.ts, twake/frontend/public/locales/en.json, twake/frontend/src/app/components/message-seen-by/message-seen-by.tsx, twake/frontend/src/app/features/messages/api/message-api-client.ts, twake/frontend/src/app/features/messages/hooks/use-message-seen-by.ts, twake/frontend/src/app/features/messages/state/atoms/message-seen-by.ts, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx, twake/frontend/src/app/views/applications/messages/message/parts/Options.tsx, twake/frontend/src/app/views/applications/messages/messages-list.tsx, twake/frontend/src/app/views/applications/messages/messages.tsx
- enabled message delivery status for all types of channels
- added an endpoint to list the users who've seen a specific message
#2472 
- adds message delivery status to all channels
- adds the ability to detect who did read a message 
- locally
=> 🌟 Added message delivery status to all channels and added seen by UI

twake/backend/node/src/services/messages/web/controllers/messages-files.ts, twake/backend/node/src/services/messages/web/controllers/views/search-files.ts
Some minor backend changes needed for next mobile release will be fastened to canary branch.
=> 🐥 Add some backend stuff to canary

twake/backend/node/src/services/workspaces/services/workspace.ts, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/Workspace/WorkspaceIdentity.tsx
=> 🛠  Fix update workspace info

twake/backend/node/src/services/console/types.ts, twake/backend/node/src/services/console/web/controller.ts, twake/frontend/src/tailwind.css
- Switch UI fix
- Console company deleted event 400 error fix
=> 🛠 Console company-deleted fix

twake/backend/node/src/services/messages/services/messages-operations.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/messages/services/threads.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/utils/messages.ts, twake/frontend/src/app/views/applications/messages/messages-list.tsx
- Fixed message delivery status being marked as read when it's just delivered
- Fixed messages with oneself not being marked as seen
- Added request delay on reading section loading
- #2487 
- fixes issues with the message delivery status
- locally
=> 🛠  improved message delivery status

twake/backend/node/src/core/platform/services/email-pusher/templates/common/_structure.eta, twake/frontend/src/app/components/online-user-status/online-user-status.tsx, twake/frontend/src/app/features/users/hooks/use-notifications.ts, twake/frontend/src/app/features/users/hooks/use-online-user.ts, twake/frontend/src/app/features/users/hooks/use-online-users.ts, twake/frontend/src/app/features/users/hooks/use-user-list.ts, twake/frontend/src/app/features/users/services/push-desktop-notification.tsx, twake/frontend/src/app/features/users/state/atoms/online-users.ts, twake/frontend/src/app/features/users/types/user.ts, twake/frontend/src/app/views/client/main-view/MainHeader/ChannelHeader/ChannelUsersHeader.tsx
=> 🛠 Fixed online and implemented last online info + notification fix

twake/backend/node/src/services/user/web/schemas.ts, twake/backend/node/src/services/user/web/types.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-users.ts, twake/backend/node/src/utils/users.ts, twake/frontend/public/locales/en.json, twake/frontend/public/locales/fr.json, twake/frontend/src/app/components/menus/menu.scss, twake/frontend/src/app/components/user-card/user-card.scss, twake/frontend/src/app/components/user-card/user-card.tsx, twake/frontend/src/app/features/users/services/current-user-service.ts, twake/frontend/src/app/features/users/types/user.ts, twake/frontend/src/app/views/applications/messages/messages.tsx
Add user deactivated notice
#2485
=> 🌟 Add user deactivated notice on Twake

twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/utils/users.ts, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/Channel.tsx, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelIntermediate.tsx, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelMenu.tsx
=> 🌟 Implemented new notification badges

twake/backend/node/src/cli/cmds/migration_cmds/channel-member-read-cursors.ts, twake/backend/node/src/services/channels/services/member/service.ts
- Added migration command to fix channel members read sections.
- #2521 
- old messages are not marked as seen by anyone.
- locally
=> 🌟 added migration command to set every old messages as seen by everyone in public channels

twake/backend/node/src/core/platform/services/knowledge-graph/index.ts, twake/backend/node/src/services/workspaces/web/controllers/workspace-users.ts, twake/frontend/src/app/views/applications/messages/message/parts/Options.tsx, twake/frontend/src/app/views/client/channels-bar/Parts/Channel/ChannelIntermediate.tsx
=> 🛠 Fix potential not set cache

twake/backend/node/src/core/platform/services/realtime/services/room-manager.ts, twake/backend/node/src/services/messages/entities/messages.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/online/service/index.ts, twake/backend/node/src/services/user/realtime.ts, twake/backend/node/src/services/user/services/users/service.ts, twake/backend/node/src/services/user/web/controller.ts, twake/backend/node/src/utils/messages.ts, twake/frontend/public/locales/en.json, twake/frontend/src/app/components/channels-selector/index.tsx, twake/frontend/src/app/components/forward-message/index.tsx, twake/frontend/src/app/components/inputs/checkbox.js, twake/frontend/src/app/features/messages/types/message.ts, twake/frontend/src/app/molecules/quoted-content/index.tsx, twake/frontend/src/app/views/applications/messages/input/input.tsx, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx, twake/frontend/src/app/views/applications/messages/message/parts/Options.tsx, twake/frontend/src/app/views/applications/messages/messages.tsx
=> 🌟 Forward messages

changelog.md
=> 📚 Update changelog.md

.github/workflows/documentation.yml
=> Fix deployment issue

.github/workflows/documentation.yml
=> 🛠 Doc test 2

Documentation/docs/.vitepress/config.js
=> Fix base in config

twake/frontend/src/app/components/file/parts/actions.tsx, twake/frontend/src/app/features/viewer/hooks/use-viewer.ts, twake/frontend/src/app/views/applications/viewer/display.tsx, twake/frontend/src/app/views/applications/viewer/other/display.tsx, twake/frontend/src/app/views/applications/viewer/other/editors-service.ts
related to https://github.com/linagora/Twake/issues/2583
connector: https://github.com/linagora/twake-plugin-onlyoffice
=> 🌟 Added other Document viewer display

twake/backend/node/src/core/platform/services/knowledge-graph/api-client.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/messages/services/threads.ts
=> 🛠 Update thread counter in realtime

Documentation/docs/internal-documentation/backend-services/documents/rest-apis.md, twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/web/controllers/documents.ts, twake/backend/node/src/services/documents/web/routes.ts, twake/backend/node/src/services/documents/web/schemas.ts, twake/backend/node/yarn.lock, twake/frontend/src/app/features/drive/api-client/api-client.ts, twake/frontend/src/app/features/drive/hooks/use-drive-actions.tsx, twake/frontend/src/app/features/drive/hooks/use-drive-item.tsx, twake/frontend/src/app/features/drive/hooks/use-drive-upload.tsx, twake/frontend/src/app/views/applications/drive/header-path.tsx, twake/frontend/src/app/views/applications/drive/index.tsx, twake/frontend/src/app/views/applications/drive/item-row/document-row.tsx, twake/frontend/src/app/views/applications/drive/item-row/folder-row.tsx, twake/frontend/src/app/views/applications/drive/modals/create-modal/create-folder.tsx, twake/frontend/src/app/views/applications/drive/modals/selector/index.tsx, twake/frontend/src/app/views/applications/drive/modals/versions/index.tsx
=> 🎨 Continue Drive UI

twake/backend/node/src/services/documents/entities/file-version.ts, twake/backend/node/src/services/documents/services/engine/extract-keywords.ts, twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/backend/node/src/services/documents/web/controllers/documents.ts, twake/frontend/src/app/features/drive/hooks/use-drive-upload.tsx, twake/frontend/src/app/features/drive/types.ts
- fixes item version fetching.
- fixes item size calculation and update.
- fixes item version creation.
- calculates file metadata and updates on the backend too ( override frontend ).
- updated the frontend drive item creation and version creation.
=> Version fixes

twake/backend/node/src/services/documents/entities/drive-file.ts, twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/frontend/src/app/views/applications/drive/modals/versions/index.tsx
- fixed moving to itself
- auto rename
- file size
- update of parents
- versions fetching
- remove unused old fields
- prevent moving a folder to one of its derived children
=> 📁 Drive fixes

twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/backend/node/src/services/documents/web/controllers/documents.ts, twake/frontend/src/app/views/applications/drive/modals/confirm-trash/index.tsx
- changed the way the delete is handled in the frontend, it uses the remove method instead of the update.
#2716 
- Fixes not being able to move folders to the trash in the drive.
- locally
https://user-images.githubusercontent.com/6764881/216073495-efc12d59-0b4c-4a6e-b67b-186ccab226c1.mp4
=> 📁 #2716 Fixed drive item delete

twake/backend/node/src/services/documents/utils.ts, twake/backend/node/src/services/documents/web/controllers/documents.ts, twake/backend/node/src/services/user/services/companies.ts, twake/frontend/src/app/components/search-popup/parts/drive-item-result.tsx, twake/frontend/src/app/features/drive-twake/api-client/api-client.ts, twake/frontend/src/app/features/drive/hooks/use-drive-item.tsx, twake/frontend/src/app/features/viewer/hooks/use-viewer.ts, twake/frontend/src/app/views/applications/drive/browser.tsx, twake/frontend/src/app/views/applications/drive/header-path.tsx, twake/frontend/src/app/views/applications/drive/item-row/common.tsx, twake/frontend/src/app/views/applications/drive/item-row/document-row.tsx, twake/frontend/src/app/views/applications/drive/item-row/folder-row.tsx, twake/frontend/src/app/views/applications/drive/modals/update-access/internal-access.tsx, twake/frontend/src/app/views/applications/drive/twake-tab-configuration.tsx, twake/frontend/src/app/views/client/main-view/AppView/AppView.tsx
=> 📁 Several Drive fixes

twake/backend/node/src/services/documents/utils.ts, twake/frontend/src/app/features/applications/hooks/use-company-applications.ts, twake/frontend/src/app/features/applications/state/company-applications.ts, twake/frontend/src/app/features/auth/jwt-storage-service.ts, twake/frontend/src/app/features/drive/hooks/use-drive-preview.ts, twake/frontend/src/app/features/drive/hooks/use-drive-upload.tsx, twake/frontend/src/app/views/applications/drive/browser.tsx, twake/frontend/src/app/views/applications/drive/components/select-users.tsx, twake/frontend/src/app/views/applications/drive/index.tsx, twake/frontend/src/app/views/applications/drive/modals/create/index.tsx, twake/frontend/src/app/views/applications/drive/modals/update-access/internal-access.tsx, twake/frontend/src/app/views/applications/drive/shared.tsx, twake/frontend/src/app/views/applications/viewer/drive-display.tsx, twake/frontend/src/app/views/client/main-view/MainView.tsx
=> 📁 Drive fix QA issues

twake/backend/node/src/services/applications/web/controllers/company-applications.ts, twake/frontend/src/app/views/applications/drive/browser.tsx, twake/frontend/src/app/views/applications/drive/modals/create/index.tsx
- Issue on removing apps
- Popup not closing when selecting empty app file
=> 📁 Drive qa fix 3

twake/backend/node/src/services/applications-api/web/controllers/index.ts, twake/frontend/src/app/features/applications/hooks/temp-fix.ts, twake/frontend/src/app/features/applications/hooks/use-applications.ts, twake/frontend/src/app/features/applications/hooks/use-company-applications.ts, twake/frontend/src/app/features/viewer/hooks/use-viewer.ts, twake/frontend/src/app/views/applications/viewer/controls.tsx, twake/frontend/src/app/views/applications/viewer/drive-display.tsx, twake/frontend/src/app/views/applications/viewer/other/controls.tsx, twake/frontend/src/app/views/applications/viewer/other/editors-service.ts
=> 📁 Implement #2766

twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/backend/node/src/services/files/services/index.ts, twake/frontend/src/app/atoms/modal/index.tsx, twake/frontend/src/app/features/drive/hooks/use-drive-actions.tsx, twake/frontend/src/app/views/applications/drive/context-menu.tsx, twake/frontend/src/app/views/applications/drive/modals/properties/index.tsx, twake/frontend/src/app/views/applications/drive/modals/update-access/index.tsx, twake/frontend/src/app/views/applications/drive/modals/update-access/internal-access.tsx, twake/frontend/src/app/views/applications/messages/input/parts/InputOptions.tsx
Regressions:
- No feedback after editing access management modal
- No thumbnails nowhere now (in messages and in drive, something broke)
- Minor issue on context menu when only one item is selected
Other:
- Improved a bit access management clarity
=> 📁 Improve access modal, fix thumbnail, fix state management

twake/backend/node/src/services/documents/entities/file-version.ts, twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/frontend/src/app/features/drive/hooks/use-drive-realtime.tsx, twake/frontend/src/app/features/global/hooks/use-realtime.ts, twake/frontend/src/app/views/applications/drive/browser.tsx, twake/frontend/src/app/views/applications/drive/context-menu.tsx, twake/frontend/src/app/views/applications/drive/modals/properties/index.tsx
- Fix renaming keep extension
- Fix thumbnails not being set after onlyoffice edit
=> 📁 Fix renaming and thumbnail

README.md, twake/backend/node/src/cli/cmds/migration_cmds/php-drive-file/drive-migrator-service.ts, twake/backend/node/src/services/documents/utils.ts, twake/frontend/src/app/views/applications/drive/browser.tsx
=> 📂Fix public link backend

twake/frontend/src/app/components/channel-members-list/channel-members-modal.tsx
Fix no scroll in twake channel members list
=> 🩹 Update channel-members-modal.tsx

twake/frontend/src/app/views/applications/drive/context-menu.tsx, twake/frontend/src/app/views/applications/drive/index.tsx, twake/frontend/src/app/views/applications/drive/shared.tsx
- Fix shared dark mode (pasted from TDrive repo)
- Fix apps not loaded in shared links (pasted from TDrive repo)
- Fix public links being null (pasted from TDrive repo)
=> 🛠 Fix drive public links

twake/backend/node/src/services/channels/web/routes.ts
=> Revert "🐛 Debug: added debug endpoint for channels list"
