twake/backend/core/src/Twake/Core/Services/TwakeMailer.php
Add check of DKIM config (isset and not empty) to avoid throwing of a fatal error if DKIM isn't configured (`Fatal error: Uncaught Swift_SwiftException: Unable to load DKIM Private Key [error:0607A082:digital envelope routines:EVP_CIPHER_CTX_ set_key_length:invalid key length] in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Signers/DKIMSigner.php on line 675`)
=> ♻️ Allow unconfigured DKIM in mailer

twake/backend/core/src/Twake/Core/Command/ScheduledNotificationsConsumeTimetable.php
Fixes #97 by adding a 100ms sleep to the loop which calls consumeSheds over and over.
=> Fix high idle CPU usage

twake/backend/core/app/Configuration/Parameters.php.dist, twake/docker-compose.yml.dist, twake/docker-compose.yml.dist.dev, twake/docker-compose.yml.dist.tests, twake/docker/twake-node/entrypoint.sh
Update the dockers, the new way of working with docker will be:
```
cd twake
cp docker-compose.yml.dev docker-compose.yml
docker-compose up -d
```
If you change your files, it will be updated on the docker simultaneously (watcher is on in dev mode).
To run tests or any commands:
```
docker-compose exec node npm run test
docker-compose exec node npm run lint
...
```
In the app default parameters, it will be necessary to update hosts. ScyllaDB is available through `["scylladb:9042", "scylladb2:9042"]` (two nodes).
=> Update docker for node developers

twake/backend/core/app/Configuration/Parameters.php.dist, twake/docker-compose.yml.dist, twake/docker-compose.yml.dist.dev, twake/docker-compose.yml.dist.tests
There was an error in the seeds of ScyllaDB nodes in docker-composes.
Also an error in how Cassandra for PHP discover nodes (it only need one node to discover the other ones)
=> 🐳 Fix bad scylladb seeds

twake/backend/node/src/core/platform/framework/api/crud-service.ts, twake/backend/node/src/core/platform/framework/decorators/realtime/created.ts, twake/backend/node/src/core/platform/framework/decorators/realtime/deleted.ts, twake/backend/node/src/core/platform/framework/decorators/realtime/index.ts, twake/backend/node/src/core/platform/framework/decorators/realtime/updated.ts, twake/backend/node/src/core/platform/services/webserver/types.ts, twake/backend/node/src/services/channels/realtime.ts, twake/backend/node/src/services/channels/services/cassandra.ts, twake/backend/node/src/services/channels/services/index.ts, twake/backend/node/src/services/channels/services/mongo.ts, twake/backend/node/src/services/channels/types.ts, twake/backend/node/src/services/channels/web/controller.ts, twake/backend/node/src/services/channels/web/routes.ts, twake/backend/node/test/e2e/channels/channels.realtime.spec.ts, twake/backend/node/test/e2e/channels/channels.rest.spec.ts
With the help of the execution context, we will be able to push realtime updates to the right websocket rooms.
Also, this PR introduces a wrapper for the ChannelService implementation so that mongo and cassandra implementation does not have to deal with decorators.
=> #470 Introduce execution context in CRUD services

twake/frontend/src/app/services/Collections/Collection.ts, twake/frontend/src/app/services/Collections/Collections.ts, twake/frontend/src/app/services/Collections/Storage.ts, twake/frontend/src/app/services/Collections/Transport/CollectionTransport.ts, twake/frontend/src/app/services/Collections/Transport/CollectionTransportSockets.ts, twake/frontend/src/app/services/Collections/Transport/Transport.ts, twake/frontend/src/app/services/Collections/Transport/TransportHTTP.ts, twake/frontend/src/app/services/Collections/Transport/TransportSocket.ts, twake/frontend/src/app/services/CollectionsReact/Collections.ts, twake/frontend/src/app/services/CollectionsReact/__tests__/CollectionReact.test.tsx, twake/frontend/src/app/services/Observable/Observable.ts
- Use the websocket details from GET calls to initialise websockets
- Auto-rejoin websocket rooms on disconnection
- Offline mode with IndexedDb (fallback to MemoryDB) 
- If no configuration, no http request are done
- Apply linter to Collections and Observables
=> ↔️ Use websocket details for transport

.github/workflows/backend.yml, .github/workflows/docker.yml, .github/workflows/saas-update-backend.yml, .github/workflows/saas-update-front.yml, twake/docker/twake-nginx-php-only/Dockerfile, twake/docker/twake-nginx/Dockerfile, twake/docker/twake-php/Dockerfile, twake/frontend/package.json
The main goal of this PR is to be able to build the Docker image on latest release of Debian (Buster) & Ubuntu (20.04).
The upgrade of the version used in the Github Actions is to follow those supported versions.  
Warning: Github Action `latest` tag for Ubuntu is wrong (18.04 instead of 20.04)
=> Fix compilation failure when building PHP Docker image

twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts, twake/backend/node/src/services/notifications/entities/channel-thread-users.ts, twake/backend/node/src/services/notifications/services/engine/processors/new-channel-message/index.ts, twake/backend/node/src/services/notifications/services/preferences/service.ts, twake/backend/node/test/unit/services/notifications/services/engine/processors/new-channel-message/index.test.ts
To fix, drop the `channel_thread_users` table and recreate it by restarting the node backend
=> #727 Notify users in threads

twake/backend/node/src/core/platform/services/pubsub/amqp/client.ts, twake/backend/node/src/core/platform/services/pubsub/amqp/manager.ts, twake/backend/node/src/core/platform/services/pubsub/amqp/pubsub.ts, twake/backend/node/src/core/platform/services/pubsub/amqp/pubsubclient.ts, twake/backend/node/src/core/platform/services/pubsub/api.ts
Note:
This can not be automatically applied to current production stuff: We need to do some manual operations before setting queues TTL because Rabbit will not like if we try to bind stuff with new properties.
=> Add TTL on Rabbit publish & subscribe

twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/node/src/services/channels/entities/channel-activity.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/channel/service.ts, twake/backend/node/src/services/channels/services/pubsub/new-channel-activity/index.ts, twake/backend/node/src/services/channels/types.ts
New sub fields were added to last_message field of the channel entity
last_message field currently contains 4 fields: sender (user_id), date, title and text (username: message text). But currently in mobile application we need a little different data:
1. We need username separately (not as part of the text sub field)
2. Text sub field should contain only message itself without sender's name
In order to avoid breaking mobile notifications which is triggered by the same event as for updating last_message for the channel, I only appended the required fields to RabbitMQ data.
https://github.com/linagora/Twake-Mobile/issues/433
New mobile application design requires the above mentioned new fields
It wasn't tested
Addition of the new fields to channel entity's last_message column, adjusted …
=> Added additional subfields to last_message field of the channel

twake/backend/node/src/core/platform/services/webserver/index.ts
If set to true, swagger doesn't work on installations which run on
insecure http connections
staticSCP options if set to true, forces all the subsequent requests to swagger resources to be redirected to secure connection, which on local installation without SSL support won't work. Setting it to false doesn't affect security much, because it's just a public documentation.
Run it on local instance, nothing breaks.
=> Set staticCSP to false in fastify-swagger options

twake/backend/core/src/Twake/Discussion/Controller/Discussion.php, twake/backend/core/src/Twake/Discussion/Services/MessageSystem.php, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts, twake/backend/node/src/core/platform/services/database/services/orm/manager.ts, twake/backend/node/src/core/platform/services/database/services/orm/types.ts, twake/backend/node/src/services/channels/entities/channel-member.ts, twake/backend/node/src/services/channels/entities/channel.ts, twake/backend/node/src/services/channels/entities/tab.ts, twake/backend/node/src/services/files/entities/file.ts, twake/backend/node/src/services/messages/api.ts, twake/backend/node/src/services/messages/entities/messages.ts, twake/backend/node/src/services/messages/entities/threads.ts, twake/backend/node/src/services/messages/services/engine/index.ts, twake/backend/node/src/services/messages/services/engine/processors/channel-view/index.ts, twake/backend/node/src/services/messages/services/engine/processors/message-to-notifications/index.ts, twake/backend/node/src/services/messages/services/messages/operations.ts, twake/backend/node/src/services/messages/services/messages/service.ts, twake/backend/node/src/services/messages/services/messages/utils.ts, twake/backend/node/src/services/messages/services/threads/service.ts, twake/backend/node/src/services/messages/services/views/service.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/messages.ts, twake/backend/node/test/e2e/messages/messages.user-bookmarks.realtime.spec.ts, twake/backend/node/test/e2e/messages/messages.user-bookmarks.spec.ts, twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx, twake/frontend/src/app/services/user/user.js, twake/frontend/yarn.lock
=> 🛠  Messages to node #1301 bux fixing

twake/backend/node/src/core/crypto/index.ts, twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts, twake/backend/node/src/core/platform/services/database/services/orm/decorators/entity.ts, twake/backend/node/src/core/platform/services/database/services/orm/types.ts, twake/backend/node/src/services/user/entities/user.ts
This is used for the user table as a temporary solution. Reminder: the goal is to not use any advanced indexes on Scylla or Cassandra because Cassandra marked them as experimental, then depreciated.
=> 🛠 Ability to create global indexes

twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelTemplateEditor.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Modals/ChannelWorkspaceEditor.tsx
https://user-images.githubusercontent.com/36481167/128495157-d4140edc-0a5c-4736-816b-494670c6dbbf.mp4
https://user-images.githubusercontent.com/36481167/128510714-e52ccaf8-6e05-4b1a-913a-94a2654e8d13.mp4
=> #1533 Allow to edit the channel description field when user leave it blank

twake/docker/nginx-static-yarn/Dockerfile
'build-nginx' Github Actions is failing.
The root cause comes from the change of Debian repositories (new stable version introduce August the 14th),
then the GPG keys had changed:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```
So we have to regenerate the root image used in the underlying Docker container.
The problem is that Certbot has changed and the initial script is no more available,
we should use pip to install it instead.
=> certbot-auto script is no more available

twake/backend/node/src/core/platform/services/tracker/index.ts
Our users can enable anonymous tracking for us to keep track of the platform usage. But currently all ids are "anonymous" (so we cannot count unique events).
Now we will have md5(userId) as anonymous id.
=> 📈 Fix anonymousId in tracker

twake/frontend/src/app/app.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsApps/ChannelsApps.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/ChannelsBar.tsx, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CompanyHeader/CompanyHeader.scss, twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/CompanyHeader/CompanyHeader.tsx, twake/frontend/src/app/scenes/Client/Client.tsx, twake/frontend/src/app/scenes/Client/MainView/MainView.tsx, twake/frontend/src/app/scenes/Client/SideBars.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/Components/Workspace/WorkspaceIcon.tsx, twake/frontend/src/app/scenes/Client/WorkspacesBar/WorkspacesBar.scss, twake/frontend/src/app/scenes/Client/WorkspacesBar/WorkspacesBar.tsx, twake/frontend/src/app/theme.less
The purpose of this PR is to create a new side bar for the lazy loading with ant design skeleton
This PR is about to change the order from rendering. For now order is Main view -> ChannelBar -> Workspace bar and with this PR the order will become Workspace -> ChannelBar -> Main view 
This is an extension of issue #1734 : https://github.com/linagora/Twake/pull/1739
=> ⚡️ #1734bis: Improve sideBar lazy loading 

twake/frontend/src/app/scenes/Client/MainView/Tabs/DefaultChannelTab.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tab.tsx, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.scss, twake/frontend/src/app/scenes/Client/MainView/Tabs/Tabs.tsx
In Twake the tabBar is really slow due to the use of ant design with a lot of over writing to make them match the Twake use of tabs
Create new components for the tab not using ant design anymore in purpose to make Twake faster 
https://github.com/linagora/Twake/issues/1763
=> ⚡️ #1763bis:  Convert tab bar from ant design components to homemade components

twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx
You need to reload twake before seeing changes.
To be able to see the changes, we need to implement real time on the `useUser` hook after the #1815 pull request is merged
=> #1820 Fix user status in message header component

twake/backend/node/src/services/console/clients/remote.ts, twake/backend/node/src/services/console/web/controller.ts, twake/backend/node/src/services/user/entities/company.ts, twake/backend/node/src/services/user/services/index.ts, twake/backend/node/src/services/user/web/schemas.ts, twake/backend/node/src/services/user/web/types.ts, twake/backend/node/src/services/workspaces/web/routes.ts, twake/backend/node/test/e2e/users/users.spec.ts, twake/backend/node/test/e2e/workspaces/workspace-pending-users.spec.ts, twake/frontend/public/locales/de.json, twake/frontend/public/locales/en.json, twake/frontend/public/locales/es.json, twake/frontend/public/locales/fr.json, twake/frontend/public/locales/ru.json, twake/frontend/src/app/components/auto-height/auto-height.js, twake/frontend/src/app/components/locked-features-components/locked-invite-alert/index.tsx, twake/frontend/src/app/features/channels/api/channel-api-client.ts, twake/frontend/src/app/features/companies/types/company.ts, twake/frontend/src/app/features/global/services/feature-toggles-service.ts, twake/frontend/src/app/views/client/channels-bar/Parts/CurrentUser/CurrentUser.js, twake/frontend/src/app/views/client/popup/AddUser/AddUserByEmail.tsx, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartner.tsx, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Pending.tsx
https://user-images.githubusercontent.com/36481167/151386558-2cc0a515-c367-41a3-aabe-568a99f6e55e.mp4
https://user-images.githubusercontent.com/36481167/152163765-12bd069f-b85c-4983-97e2-1e2dbd920e48.mp4
=> #1900 Workspace members invite fixes

twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/query-builder.ts, twake/backend/node/src/core/platform/services/search/adapters/elasticsearch/index.ts, twake/backend/node/src/core/platform/services/search/repository.ts, twake/backend/node/src/services/channels/provider.ts, twake/backend/node/src/services/channels/services/member/service.ts, twake/backend/node/src/services/messages/api.ts, twake/backend/node/src/services/messages/entities/messages.search.ts, twake/backend/node/src/services/messages/index.ts, twake/backend/node/src/services/messages/services/views/service.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/views.ts, twake/backend/node/src/services/messages/web/index.ts, twake/backend/node/src/services/messages/web/routes.ts, twake/backend/node/src/services/workspaces/api.ts, twake/backend/node/src/services/workspaces/services/workspace/service.ts, twake/backend/node/test/e2e/messages/messages.search.spec.ts
https://github.com/linagora/Twake/issues/2007
=> Search improve

twake/frontend/src/app/features/users/api/user-api-client.ts
=> #2026 Fix error 'Concat is not a function' in UserAPIClient

twake/frontend/src/app/features/users/hooks/use-search-user-list.ts, twake/frontend/src/app/features/users/types/user.ts, twake/frontend/src/app/features/workspaces/types/workspace.ts, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartner.tsx, twake/frontend/src/app/views/client/popup/WorkspaceParameter/Pages/WorkspacePartnerTabs/Members.tsx
Fixed workspace users page using the new useUserSearch hook.
Note that there is still more refactoring to do on this pages it is very difficult to work in it.
#2115
=> 🛠 #2115 Fix workspace user search

twake/backend/node/src/core/platform/services/storage/index.ts
It was related to reused decipher stream.
=> 🛠 Fix multi-chunks file download bug

twake/backend/node/src/services/messages/services/engine/processors/links/index.ts
- fixes a bug related to saving link previews to wrong thread introduced in https://github.com/linagora/Twake/pull/2204
https://github.com/linagora/Twake/issues/2139
- bug fix
- locally
https://user-images.githubusercontent.com/6764881/171648821-d85cee2b-fdb6-4798-861c-cd9aeb74cecc.mp4
=> 🛠 fixed messages link previews being saved in the wrong context thread

twake/backend/node/src/services/messages/services/utils.ts, twake/backend/node/src/services/previews/services/links/processing/link.ts, twake/backend/node/src/services/previews/types.ts, twake/backend/node/test/unit/services/previews/services/links/processing/links.test.ts, twake/frontend/src/app/features/messages/types/message.ts, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.scss, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.tsx, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx
- adds the link preview 
https://github.com/linagora/Twake/issues/2217
- display previews for links detected in messages.
- locally
https://user-images.githubusercontent.com/6764881/171865977-4d9955cd-8f2a-423b-8c37-5b4400c3c79a.mp4
=> 🌟 Added link preview in the frontend

twake/backend/node/src/cli/cmds/search_cmds/index_all.ts, twake/backend/node/src/core/platform/services/search/adapters/mongosearch/index.ts, twake/backend/node/src/core/platform/services/search/adapters/mongosearch/search.ts, twake/backend/node/src/services/applications/entities/application.search.ts, twake/backend/node/src/services/channels/entities/channel.search.ts, twake/backend/node/src/services/channels/web/controllers/channel.ts, twake/backend/node/src/services/messages/api.ts, twake/backend/node/src/services/messages/entities/message-files.search.ts, twake/backend/node/src/services/messages/entities/message-files.ts, twake/backend/node/src/services/messages/entities/messages.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/messages/services/views.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/views.ts, twake/backend/node/src/services/messages/web/routes.ts, twake/backend/node/src/services/user/entities/user.search.ts, twake/backend/node/test/e2e/channels/channels.search.spec.ts, twake/backend/node/test/e2e/messages/messages.files.search.spec.ts, twake/backend/node/test/e2e/messages/messages.files.spec.ts, twake/backend/node/test/e2e/messages/messages.search.spec.ts, twake/backend/node/test/e2e/messages/utils.ts, twake/backend/node/test/e2e/run-all.js, twake/backend/node/test/e2e/users/users.search.spec.ts
#2221
Doc is here: https://www.notion.so/linagora/Rest-APIs-232eb8e51c3743ccbb7aa3534a5a7db9
=> 🌟 Improve search endpoint

twake/backend/node/src/services/messages/api.ts, twake/backend/node/src/services/messages/entities/messages.ts, twake/backend/node/src/services/messages/services/messages-operations.ts, twake/backend/node/src/services/messages/services/messages.ts, twake/backend/node/src/services/messages/types.ts, twake/backend/node/src/services/messages/web/controllers/messages.ts, twake/backend/node/src/services/messages/web/routes.ts, twake/frontend/src/app/features/messages/api/message-api-client.ts, twake/frontend/src/app/features/messages/hooks/use-message.ts, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.scss, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.tsx
- adds the ability to remove a link preview from the generated previews for a given message
https://github.com/linagora/Twake/issues/2235
- allows users to control what previews to keep
- locally
https://user-images.githubusercontent.com/6764881/172447416-39a3e056-695b-4e0d-b971-80965071ebde.mp4
=> 🌟 Added remove link preview

twake/backend/node/src/services/messages/web/controllers/views/search-files.ts, twake/frontend/src/app/components/channel-avatar/channel-avatar.tsx, twake/frontend/src/app/components/search-popup/parts/channels-result.tsx, twake/frontend/src/app/components/search-popup/parts/messages-result.tsx, twake/frontend/src/app/components/search-popup/parts/recent-channels-and-contacts.tsx, twake/frontend/src/app/components/search-popup/search-popup.scss, twake/frontend/src/app/components/search-popup/tabs/all/search.tsx, twake/frontend/src/app/components/search-popup/tabs/files/index.tsx, twake/frontend/src/app/features/global/services/search-service.ts, twake/frontend/src/app/features/messages/api/message-api-client.ts
The width of 100vw 
bug: A "0" appear on the search 
fixed backend for recents search (when the search string is not defined)
removed mutiple avatars for chats
=> 2258 bug fixes

twake/frontend/src/app/features/messages/hooks/use-ephemeral-messages.ts, twake/frontend/src/app/views/applications/messages/input/parts/EphemeralMessages.tsx
=> 🛠 Fix ephemeral messages display

twake/backend/node/src/services/previews/services/links/processing/image.ts, twake/backend/node/src/services/previews/services/links/processing/link.ts, twake/backend/node/src/services/previews/services/links/processing/service.ts, twake/backend/node/src/services/previews/utils.ts, twake/backend/node/test/unit/services/previews/services/links/processing/images.test.ts, twake/backend/node/test/unit/services/previews/services/links/processing/links.test.ts, twake/backend/node/test/unit/services/previews/services/links/processing/service.test.ts
- Added support for image link preview
- checks the size of the content to preview and sets a maximum of 5 MB per link
- adds a 5 seconds timeout when generating previews 
https://github.com/linagora/Twake/issues/2280
https://github.com/linagora/Twake/issues/2278
- missing support for image link previews
- URLs to preview are not checked and could cause a problem for big files
- locally
https://user-images.githubusercontent.com/6764881/173596737-a4d3f0d0-338b-4d86-966c-56e0924189dc.mp4
=> 🌟 Added support for image link preview and added a limit and timeout to links #2280 #2278

twake/backend/node/src/services/messages/services/messages-operations.ts, twake/frontend/src/app/views/applications/messages/message/parts/LinkPreview.tsx
- adds frontend and backend checks to only allow the message author to delete a link preview
https://github.com/linagora/Twake/issues/2298
- fixes a bug
- locally
=> 🛠 Fixed message link previews being removable by everyone

twake/backend/node/src/services/channels/entities/channel-member.ts, twake/backend/node/src/services/channels/web/controllers/member.ts
Add user object in channel member get endpoint
#2279 
- localy
=> :star2: Add user object in channel member get endpoint

twake/backend/node/src/services/previews/services/links/processing/link.ts, twake/backend/node/src/services/previews/services/links/processing/service.ts, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx
- backend: skip previews that don't have enough information to preview ( at least should have a title or description or image )
- backend: skip the rest of the generation process if no title and no image and no description are found ( gains time cause no favicon fetching and so on ).
- frontend: filter out invalid previews  
- #2397 
- some links have previews with just the domain, basically an empty preview.
- locally
=> 🛠  skip message link previews if there is nothing to preview

twake/backend/node/src/services/console/clients/remote.ts
=> 🛠 Fix console deleted user sync

twake/frontend/src/app/components/channel-attachement-list/parts/channel-attachment.tsx, twake/frontend/src/app/features/channels/hooks/use-channel-media-files.ts
- Fixes having files and medias from previous channels
#2429 
- fixes a bug where users can see media that doesn't belong to the current channel.
- locally
=> 🛠  Fixed channel medias and files view having results from previous channels

twake/frontend/public/locales/en.json, twake/frontend/src/app/components/quoted-message/quoted-message.tsx, twake/frontend/src/app/features/messages/hooks/use-message-editor.ts, twake/frontend/src/app/molecules/message-quote/index.tsx, twake/frontend/src/app/molecules/quoted-content/index.tsx, twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx
- adds the ability to quote reply attachments.
- closes the quote message indicator after sending the message. 
#2456 
#2460
- solves messages with only attached files appearing empty when quoted.
- fixes quote reply indicator not disappearing when sending messages.
- locally
https://user-images.githubusercontent.com/6764881/187158656-76fc519b-e455-49f2-b03b-bbd922a34992.mp4
=> 🛠️ quoted reply improvements

twake/docker-compose.dev.mongo.yml
- changed the exposed backend port to 4000
- the MongoDB dev backend port is exposed to port 3000 which is the default port for the `craco start` leading  to errors and confusion when you run the frontend first and vice versa.
- locally
=> 🛠  fixed backend binding the default frontend port

twake/frontend/src/app/components/channel-attachement-list/parts/channel-files.tsx, twake/frontend/src/app/components/channel-attachement-list/parts/channel-medias.tsx, twake/frontend/src/app/features/channels/hooks/use-channel-media-files.ts
- changed when media and files list are loaded using `useEffect` hook.
- added conditions to the load more function to prevent infinite loops
#2403 
- Fixes a bug when you send new files or media in the channel, the list does not update.
- locally
https://user-images.githubusercontent.com/6764881/189665125-63ff8526-b22d-4d77-bf88-daf8362c9389.mp4
=> 🛠  fixed channel medias and files not getting updated when new files are sent

twake/frontend/src/app/views/applications/messages/messages-list.tsx
- added a check for the browser tab state before sending the read message request
- #2472 
- Fixes messages being marked as read when the browser tab is not active
- locally
https://user-images.githubusercontent.com/6764881/190388621-13685427-1a8e-429d-b7f3-da0d1ec45718.mp4
=> 🛠  message marked as read when the message is received and the tab is not active

twake/backend/node/src/services/notifications/web/controllers/preferences.ts, twake/frontend/src/app/views/client/popup/UserParameter/Pages/Notifications.tsx
Fix white page when there is no preferences
#2494
localy
=> 🛠  Fix white page when no preferences

twake/backend/node/src/services/files/services/index.ts, twake/backend/node/src/services/messages/services/views.ts
Done it on search files and get recent files endpoints
=> 🛠 Do not return files that doesn't exists anymore

twake/docker/twake-nginx/entrypoint.sh
This should let docker show nginx logs in the container output (`docker logs` and `docker compose logs`)
=> Added symlinks for docker log collector

Documentation/docs/internal-documentation/backend-services/knowledge-graph/README.md, twake/backend/node/config/default.json, twake/backend/node/src/core/platform/services/knowledge-graph/index.ts, twake/backend/node/src/core/platform/services/knowledge-graph/types.ts, twake/backend/node/src/services/general/index.ts, twake/backend/node/src/services/knowledge-graph-web/index.ts, twake/backend/node/src/services/knowledge-graph-web/web/index.ts, twake/backend/node/src/services/knowledge-graph-web/web/routes.ts
#2629 
We open an endpoint at:
`POST https://api.twake.app/internal/services/knowledge-graph/v1/push`
Authorised by a Token authorization header:
`Authorization: Token {some token defined together}`
And with the following data in JSON:
```
{
events: [KnowledgeGraphCallbackEvent, KnowledgeGraphCallbackEvent, KnowledgeGraphCallbackEvent, ...]
}
type KnowledgeGraphCallbackEvent = {
recipients: {
type: "user";
id: string; // KG user id which is a md5 of the email
}[];
event: {
type: "user_tags"; //More events will be added later
data: {
//For user_tags event only
tags?: {
value: string;
weight: number;
}[];
};
};
};
```
The reply will be if everything was alright:
```
{
"status": "success"
}
```
=> 🤖 Kg changes

README.md, twake/docker-compose.onpremise.yml, twake/docker/twake-nginx/Dockerfile, twake/docker/twake-nginx/entrypoint.sh, twake/docker/twake-node/Dockerfile, twake/docker/twake-php/Dockerfile
As requested by @RomaricMourgues here: https://github.com/linagora/Twake/pull/2636#issuecomment-1337560880
This closes https://github.com/linagora/Twake/pull/2636
=> Rebasing Dockerfiles changes to `develop` branch.

twake/backend/node/src/core/platform/services/search/index.ts
This PR fixes a typo in the search service that references a non-existent logger method.
Fixes #2690.
It allows twake-node to be deployed without a search service.
I've successfully deployed twake-node locally without configuring a search service.
N/A
=> fix: `logger.warning` -> `logger.warn`

twake/frontend/src/app/features/viewer/api/viewer-api-client.ts, twake/frontend/src/app/features/viewer/hooks/use-viewer.ts, twake/frontend/src/app/views/applications/drive/item-row/document-row.tsx, twake/frontend/src/app/views/applications/viewer/viewer.tsx
adds the ability to preview the drive files.
#2710
- Fixes not being able to preview drive files using the file viewer application.
- locally
https://user-images.githubusercontent.com/6764881/215813129-21fc4eae-cad6-4188-baa8-7a54c761489d.mp4
=> 📁 added drive file preview support

twake/frontend/src/app/features/global/utils/CopyClipboard.ts
File -> Access management -> Copy public link to the clipboard, not working, nothing in clipboard when testing in staging.
The old document.execCommand('copy') method is used to execute a "copy" command on the current document. This method has been implemented in various web browsers, but the exact behavior and implementation may vary between different browsers. In some cases, the document.execCommand('copy') method may not work as expected.
=> 📁 Fix copy public link #2709

twake/backend/node/src/services/documents/entities/file-version.ts, twake/backend/node/src/services/documents/services/index.ts, twake/backend/node/src/services/documents/utils.ts, twake/backend/node/src/services/documents/web/schemas.ts, twake/frontend/src/app/features/drive/hooks/use-drive-upload.tsx, twake/frontend/src/app/features/drive/types.ts, twake/frontend/src/app/views/applications/drive/modals/versions/index.tsx
- changed the order of the primary key fields to fix the drive item versions fetching when using the Cassandra database.
#2714
- fixes versions not showing up in the drive.
- locally
=> 📁 Fixed drive item versions not working with Cassandra

twake/frontend/src/app/views/applications/drive/header-path.tsx
- changed the style of the breadcrumb navigation to remove the overflow and wrap the elements.
#2752 
solves a UI issue with the breadcrumb navigation having an overflow:
- locally
=> 📁 #2752 fixed breadcrumb navigation overflow

twake/frontend/public/index.html, twake/frontend/src/app/views/applications/drive/browser.tsx
when in canary it shows a message in the new drive to inform the user about the old and new drive.
#2757 
helps with drive migration
locally
=> added new drive migration banner to canary
